-- =====================================================================
-- iter168.18: 推し登録マスタ拡充（K-POP / アニメ / ゲーム）
-- =====================================================================
-- グッズ交換・ランダム封入・トレカ/缶バッジ/アクスタ文化が活発な
-- グループ/作品を、推し登録・グッズ登録で選べるように拡充する。

create temporary table _ihub_seed_groups (
  genre_name text not null,
  name text not null,
  aliases text[] not null default '{}',
  kind text not null,
  display_order integer not null
) on commit drop;

insert into _ihub_seed_groups (genre_name, name, aliases, kind, display_order) values
  -- K-POP: existing groups with stronger aliases / missing high-trading groups
  ('K-POP', 'Stray Kids', array['SKZ', '스트레이 키즈', 'スキズ']::text[], 'group', 5),
  ('K-POP', 'SEVENTEEN', array['세븐틴', 'セブチ', 'SVT']::text[], 'group', 6),
  ('K-POP', 'LE SSERAFIM', array['르세라핌', 'ルセラ', 'LESSERAFIM']::text[], 'group', 8),
  ('K-POP', 'ENHYPEN', array['엔하이픈', 'エナプ', 'EN-']::text[], 'group', 9),
  ('K-POP', 'TXT', array['투모로우바이투게더', 'TOMORROW X TOGETHER', 'トゥバ']::text[], 'group', 10),
  ('K-POP', 'ATEEZ', array['에이티즈', 'エイティーズ']::text[], 'group', 11),
  ('K-POP', 'ZEROBASEONE', array['ZB1', '제로베이스원', 'ゼベワン']::text[], 'group', 12),
  ('K-POP', 'RIIZE', array['라이즈', 'ライズ']::text[], 'group', 13),
  ('K-POP', 'NCT WISH', array['엔시티 위시', 'エヌシーティーウィッシュ']::text[], 'group', 14),
  ('K-POP', 'BOYNEXTDOOR', array['BND', '보이넥스트도어', 'ボネクド']::text[], 'group', 15),
  ('K-POP', 'TREASURE', array['트레저', 'トレジャー']::text[], 'group', 16),
  ('K-POP', 'NMIXX', array['엔믹스', 'エンミックス']::text[], 'group', 17),
  ('K-POP', 'BABYMONSTER', array['베이비몬스터', 'ベビモン', 'Baemon']::text[], 'group', 18),
  ('K-POP', 'ITZY', array['있지', 'イッチ']::text[], 'group', 19),
  ('K-POP', '(G)I-DLE', array['I-DLE', 'i-dle', '아이들', 'ジーアイドゥル']::text[], 'group', 20),
  ('K-POP', '&TEAM', array['앤팀', 'エンティーム']::text[], 'group', 21),
  ('K-POP', 'PLAVE', array['플레이브', 'プレイブ']::text[], 'group', 22),
  -- Anime works: blind/random badges and acrylic goods are common trading targets
  ('アニメ', 'ブルーロック', array['BLUE LOCK', 'Blue Lock', 'ブルロ']::text[], 'work', 1),
  ('アニメ', '呪術廻戦', array['Jujutsu Kaisen', 'じゅじゅつかいせん', 'じゅじゅ']::text[], 'work', 2),
  ('アニメ', '鬼滅の刃', array['Demon Slayer', 'Kimetsu no Yaiba', 'きめつ']::text[], 'work', 3),
  ('アニメ', 'ハイキュー!!', array['Haikyu!!', 'Haikyuu', 'HQ']::text[], 'work', 4),
  ('アニメ', '僕のヒーローアカデミア', array['My Hero Academia', 'ヒロアカ', 'MHA']::text[], 'work', 5),
  ('アニメ', 'チェンソーマン', array['Chainsaw Man', 'CSM']::text[], 'work', 6),
  ('アニメ', 'ダンダダン', array['DAN DA DAN', 'Dandadan']::text[], 'work', 7),
  ('アニメ', '葬送のフリーレン', array['Frieren', 'Sousou no Frieren']::text[], 'work', 8),
  ('アニメ', 'WIND BREAKER', array['ウィンドブレイカー', 'ウィンブレ']::text[], 'work', 9),
  ('アニメ', '東京リベンジャーズ', array['Tokyo Revengers', '東リベ']::text[], 'work', 10),
  ('アニメ', '【推しの子】', array['Oshi no Ko', '推しの子']::text[], 'work', 11),
  -- Game / mixed-media works with strong character goods markets
  ('ゲーム', 'プロジェクトセカイ', array['Project SEKAI', 'プロセカ', 'Colorful Stage']::text[], 'work', 1),
  ('ゲーム', 'あんさんぶるスターズ!!', array['Ensemble Stars!!', 'あんスタ', 'Enstars']::text[], 'work', 2),
  ('ゲーム', 'ディズニー ツイステッドワンダーランド', array['Twisted Wonderland', 'ツイステ']::text[], 'work', 3);

insert into public.groups_master (genre_id, name, aliases, kind, display_order)
select
  ge.id,
  sg.name,
  sg.aliases,
  sg.kind,
  sg.display_order
from _ihub_seed_groups sg
join public.genres_master ge on ge.name = sg.genre_name
on conflict (genre_id, name) do update
  set aliases = excluded.aliases,
      kind = excluded.kind,
      display_order = excluded.display_order;

create temporary table _ihub_seed_characters (
  genre_name text not null,
  group_name text not null,
  name text not null,
  aliases text[] not null default '{}',
  display_order integer not null
) on commit drop;

insert into _ihub_seed_characters (genre_name, group_name, name, aliases, display_order) values
  -- K-POP members
  ('K-POP','Stray Kids','バンチャン',array['Bang Chan','방찬','Christopher Bang']::text[],1),
  ('K-POP','Stray Kids','リノ',array['Lee Know','리노','イミンホ','이민호']::text[],2),
  ('K-POP','Stray Kids','チャンビン',array['Changbin','창빈','ソチャンビン','서창빈']::text[],3),
  ('K-POP','Stray Kids','ヒョンジン',array['Hyunjin','현진','ファンヒョンジン','황현진']::text[],4),
  ('K-POP','Stray Kids','ハン',array['HAN','한','ハンジソン','한지성']::text[],5),
  ('K-POP','Stray Kids','フィリックス',array['Felix','필릭스','ヨンボク','용복']::text[],6),
  ('K-POP','Stray Kids','スンミン',array['Seungmin','승민','キムスンミン','김승민']::text[],7),
  ('K-POP','Stray Kids','アイエン',array['I.N','아이엔','ジョンイン','양정인']::text[],8),
  ('K-POP','ENHYPEN','ジョンウォン',array['JUNGWON','정원','ヤンジョンウォン']::text[],1),
  ('K-POP','ENHYPEN','ヒスン',array['HEESEUNG','희승','イヒスン']::text[],2),
  ('K-POP','ENHYPEN','ジェイ',array['JAY','제이']::text[],3),
  ('K-POP','ENHYPEN','ジェイク',array['JAKE','제이크']::text[],4),
  ('K-POP','ENHYPEN','ソンフン',array['SUNGHOON','성훈']::text[],5),
  ('K-POP','ENHYPEN','ソヌ',array['SUNOO','선우']::text[],6),
  ('K-POP','ENHYPEN','ニキ',array['NI-KI','니키','西村力']::text[],7),
  ('K-POP','TXT','スビン',array['SOOBIN','수빈']::text[],1),
  ('K-POP','TXT','ヨンジュン',array['YEONJUN','연준']::text[],2),
  ('K-POP','TXT','ボムギュ',array['BEOMGYU','범규']::text[],3),
  ('K-POP','TXT','テヒョン',array['TAEHYUN','태현']::text[],4),
  ('K-POP','TXT','ヒュニンカイ',array['HUENINGKAI','휴닝카이']::text[],5),
  ('K-POP','LE SSERAFIM','サクラ',array['SAKURA','사쿠라','宮脇咲良']::text[],1),
  ('K-POP','LE SSERAFIM','キム・チェウォン',array['KIM CHAEWON','김채원','チェウォン']::text[],2),
  ('K-POP','LE SSERAFIM','ホ・ユンジン',array['HUH YUNJIN','허윤진','ユンジン']::text[],3),
  ('K-POP','LE SSERAFIM','カズハ',array['KAZUHA','카즈하','中村一葉']::text[],4),
  ('K-POP','LE SSERAFIM','ホン・ウンチェ',array['HONG EUNCHAE','홍은채','ウンチェ']::text[],5),
  ('K-POP','ATEEZ','ホンジュン',array['HONGJOONG','홍중']::text[],1),
  ('K-POP','ATEEZ','ソンファ',array['SEONGHWA','성화']::text[],2),
  ('K-POP','ATEEZ','ユンホ',array['YUNHO','윤호']::text[],3),
  ('K-POP','ATEEZ','ヨサン',array['YEOSANG','여상']::text[],4),
  ('K-POP','ATEEZ','サン',array['SAN','산']::text[],5),
  ('K-POP','ATEEZ','ミンギ',array['MINGI','민기']::text[],6),
  ('K-POP','ATEEZ','ウヨン',array['WOOYOUNG','우영']::text[],7),
  ('K-POP','ATEEZ','ジョンホ',array['JONGHO','종호']::text[],8),
  ('K-POP','ZEROBASEONE','ソン・ハンビン',array['SUNG HAN BIN','성한빈','ハンビン']::text[],1),
  ('K-POP','ZEROBASEONE','キム・ジウン',array['KIM JI WOONG','김지웅','ジウン']::text[],2),
  ('K-POP','ZEROBASEONE','ジャン・ハオ',array['ZHANG HAO','장하오','章昊']::text[],3),
  ('K-POP','ZEROBASEONE','ソク・マシュー',array['SEOK MATTHEW','석매튜','マシュー']::text[],4),
  ('K-POP','ZEROBASEONE','キム・テレ',array['KIM TAE RAE','김태래','テレ']::text[],5),
  ('K-POP','ZEROBASEONE','リッキー',array['RICKY','리키','沈泉锐']::text[],6),
  ('K-POP','ZEROBASEONE','キム・ギュビン',array['KIM GYU VIN','김규빈','ギュビン']::text[],7),
  ('K-POP','ZEROBASEONE','パク・ゴヌク',array['PARK GUN WOOK','박건욱','ゴヌク']::text[],8),
  ('K-POP','ZEROBASEONE','ハン・ユジン',array['HAN YU JIN','한유진','ユジン']::text[],9),
  ('K-POP','RIIZE','ショウタロウ',array['SHOTARO','쇼타로','大崎将太郎']::text[],1),
  ('K-POP','RIIZE','ウンソク',array['EUNSEOK','은석']::text[],2),
  ('K-POP','RIIZE','ソンチャン',array['SUNGCHAN','성찬']::text[],3),
  ('K-POP','RIIZE','ウォンビン',array['WONBIN','원빈']::text[],4),
  ('K-POP','RIIZE','ソヒ',array['SOHEE','소희']::text[],5),
  ('K-POP','RIIZE','アントン',array['ANTON','앤톤']::text[],6),
  ('K-POP','NCT WISH','シオン',array['SION','시온']::text[],1),
  ('K-POP','NCT WISH','リク',array['RIKU','리쿠']::text[],2),
  ('K-POP','NCT WISH','ユウシ',array['YUSHI','유우시']::text[],3),
  ('K-POP','NCT WISH','ジェヒ',array['JAEHEE','재희']::text[],4),
  ('K-POP','NCT WISH','リョウ',array['RYO','료']::text[],5),
  ('K-POP','NCT WISH','サクヤ',array['SAKUYA','사쿠야']::text[],6),
  ('K-POP','BOYNEXTDOOR','ソンホ',array['SUNGHO','성호']::text[],1),
  ('K-POP','BOYNEXTDOOR','リウ',array['RIWOO','리우']::text[],2),
  ('K-POP','BOYNEXTDOOR','ジェヒョン',array['JAEHYUN','재현','ミョンジェヒョン']::text[],3),
  ('K-POP','BOYNEXTDOOR','テサン',array['TAESAN','태산']::text[],4),
  ('K-POP','BOYNEXTDOOR','イハン',array['LEEHAN','이한']::text[],5),
  ('K-POP','BOYNEXTDOOR','ウナク',array['WOONHAK','운학']::text[],6),
  ('K-POP','TREASURE','ヒョンソク',array['CHOI HYUN SUK','최현석']::text[],1),
  ('K-POP','TREASURE','ジフン',array['JIHOON','지훈']::text[],2),
  ('K-POP','TREASURE','ヨシ',array['YOSHI','요시','金本芳典']::text[],3),
  ('K-POP','TREASURE','ジュンギュ',array['JUNKYU','준규']::text[],4),
  ('K-POP','TREASURE','ユン・ジェヒョク',array['YOON JAE HYUK','윤재혁','ジェヒョク']::text[],5),
  ('K-POP','TREASURE','アサヒ',array['ASAHI','아사히','浜田朝光']::text[],6),
  ('K-POP','TREASURE','ドヨン',array['DOYOUNG','도영']::text[],7),
  ('K-POP','TREASURE','ハルト',array['HARUTO','하루토','渡辺温斗']::text[],8),
  ('K-POP','TREASURE','パク・ジョンウ',array['PARK JEONG WOO','박정우','ジョンウ']::text[],9),
  ('K-POP','TREASURE','ソ・ジョンファン',array['SO JUNG HWAN','소정환','ジョンファン']::text[],10),
  ('K-POP','NMIXX','リリー',array['LILY','릴리']::text[],1),
  ('K-POP','NMIXX','ヘウォン',array['HAEWON','해원']::text[],2),
  ('K-POP','NMIXX','ソリュン',array['SULLYOON','설윤']::text[],3),
  ('K-POP','NMIXX','ベイ',array['BAE','배이']::text[],4),
  ('K-POP','NMIXX','ジウ',array['JIWOO','지우']::text[],5),
  ('K-POP','NMIXX','ギュジン',array['KYUJIN','규진']::text[],6),
  ('K-POP','BABYMONSTER','ルカ',array['RUKA','루카']::text[],1),
  ('K-POP','BABYMONSTER','ファリタ',array['PHARITA','파리타']::text[],2),
  ('K-POP','BABYMONSTER','アサ',array['ASA','아사']::text[],3),
  ('K-POP','BABYMONSTER','アヒョン',array['AHYEON','아현']::text[],4),
  ('K-POP','BABYMONSTER','ラミ',array['RAMI','라미']::text[],5),
  ('K-POP','BABYMONSTER','ローラ',array['RORA','로라']::text[],6),
  ('K-POP','BABYMONSTER','チキータ',array['CHIQUITA','치키타']::text[],7),
  ('K-POP','ITZY','イェジ',array['YEJI','예지']::text[],1),
  ('K-POP','ITZY','リア',array['LIA','리아']::text[],2),
  ('K-POP','ITZY','リュジン',array['RYUJIN','류진']::text[],3),
  ('K-POP','ITZY','チェリョン',array['CHAERYEONG','채령']::text[],4),
  ('K-POP','ITZY','ユナ',array['YUNA','유나']::text[],5),
  ('K-POP','(G)I-DLE','ミヨン',array['MIYEON','미연']::text[],1),
  ('K-POP','(G)I-DLE','ミンニ',array['MINNIE','민니']::text[],2),
  ('K-POP','(G)I-DLE','ソヨン',array['SOYEON','소연']::text[],3),
  ('K-POP','(G)I-DLE','ユキ',array['YUQI','우기','雨琦']::text[],4),
  ('K-POP','(G)I-DLE','シュファ',array['SHUHUA','슈화']::text[],5),
  ('K-POP','&TEAM','ケイ',array['K','케이']::text[],1),
  ('K-POP','&TEAM','フウマ',array['FUMA','후마']::text[],2),
  ('K-POP','&TEAM','ニコラス',array['NICHOLAS','니콜라스']::text[],3),
  ('K-POP','&TEAM','ウィジュ',array['EJ','의주']::text[],4),
  ('K-POP','&TEAM','ユウマ',array['YUMA','유마']::text[],5),
  ('K-POP','&TEAM','ジョウ',array['JO','조']::text[],6),
  ('K-POP','&TEAM','ハルア',array['HARUA','하루아']::text[],7),
  ('K-POP','&TEAM','タキ',array['TAKI','타키']::text[],8),
  ('K-POP','&TEAM','マキ',array['MAKI','마키']::text[],9),
  ('K-POP','PLAVE','イェジュン',array['YEJUN','예준']::text[],1),
  ('K-POP','PLAVE','ノア',array['NOAH','노아']::text[],2),
  ('K-POP','PLAVE','バンビ',array['BAMBY','밤비']::text[],3),
  ('K-POP','PLAVE','ウノ',array['EUNHO','은호']::text[],4),
  ('K-POP','PLAVE','ハミン',array['HAMIN','하민']::text[],5),
  -- Anime characters
  ('アニメ','ブルーロック','潔世一',array['Isagi Yoichi','Yoichi Isagi','イサギ']::text[],1),
  ('アニメ','ブルーロック','蜂楽廻',array['Bachira Meguru','Meguru Bachira']::text[],2),
  ('アニメ','ブルーロック','千切豹馬',array['Chigiri Hyoma','Hyoma Chigiri']::text[],3),
  ('アニメ','ブルーロック','國神錬介',array['Kunigami Rensuke','Rensuke Kunigami']::text[],4),
  ('アニメ','ブルーロック','凪誠士郎',array['Nagi Seishiro','Seishiro Nagi']::text[],5),
  ('アニメ','ブルーロック','御影玲王',array['Mikage Reo','Reo Mikage']::text[],6),
  ('アニメ','ブルーロック','糸師凛',array['Itoshi Rin','Rin Itoshi']::text[],7),
  ('アニメ','ブルーロック','糸師冴',array['Itoshi Sae','Sae Itoshi']::text[],8),
  ('アニメ','ブルーロック','馬狼照英',array['Barou Shoei','Shoei Barou']::text[],9),
  ('アニメ','ブルーロック','ミヒャエル・カイザー',array['Michael Kaiser','Kaiser']::text[],10),
  ('アニメ','呪術廻戦','虎杖悠仁',array['Yuji Itadori','Itadori Yuji']::text[],1),
  ('アニメ','呪術廻戦','伏黒恵',array['Megumi Fushiguro','Fushiguro Megumi']::text[],2),
  ('アニメ','呪術廻戦','釘崎野薔薇',array['Nobara Kugisaki','Kugisaki Nobara']::text[],3),
  ('アニメ','呪術廻戦','五条悟',array['Satoru Gojo','Gojo Satoru']::text[],4),
  ('アニメ','呪術廻戦','夏油傑',array['Suguru Geto','Geto Suguru']::text[],5),
  ('アニメ','呪術廻戦','両面宿儺',array['Sukuna','Ryomen Sukuna']::text[],6),
  ('アニメ','呪術廻戦','禪院真希',array['Maki Zenin','Zenin Maki']::text[],7),
  ('アニメ','呪術廻戦','狗巻棘',array['Toge Inumaki','Inumaki Toge']::text[],8),
  ('アニメ','呪術廻戦','七海建人',array['Kento Nanami','Nanami Kento']::text[],9),
  ('アニメ','呪術廻戦','乙骨憂太',array['Yuta Okkotsu','Okkotsu Yuta']::text[],10),
  ('アニメ','鬼滅の刃','竈門炭治郎',array['Tanjiro Kamado']::text[],1),
  ('アニメ','鬼滅の刃','竈門禰豆子',array['Nezuko Kamado']::text[],2),
  ('アニメ','鬼滅の刃','我妻善逸',array['Zenitsu Agatsuma']::text[],3),
  ('アニメ','鬼滅の刃','嘴平伊之助',array['Inosuke Hashibira']::text[],4),
  ('アニメ','鬼滅の刃','冨岡義勇',array['Giyu Tomioka']::text[],5),
  ('アニメ','鬼滅の刃','胡蝶しのぶ',array['Shinobu Kocho']::text[],6),
  ('アニメ','鬼滅の刃','煉獄杏寿郎',array['Kyojuro Rengoku']::text[],7),
  ('アニメ','鬼滅の刃','宇髄天元',array['Tengen Uzui']::text[],8),
  ('アニメ','鬼滅の刃','時透無一郎',array['Muichiro Tokito']::text[],9),
  ('アニメ','鬼滅の刃','甘露寺蜜璃',array['Mitsuri Kanroji']::text[],10),
  ('アニメ','ハイキュー!!','日向翔陽',array['Shoyo Hinata']::text[],1),
  ('アニメ','ハイキュー!!','影山飛雄',array['Tobio Kageyama']::text[],2),
  ('アニメ','ハイキュー!!','月島蛍',array['Kei Tsukishima']::text[],3),
  ('アニメ','ハイキュー!!','山口忠',array['Tadashi Yamaguchi']::text[],4),
  ('アニメ','ハイキュー!!','孤爪研磨',array['Kenma Kozume']::text[],5),
  ('アニメ','ハイキュー!!','黒尾鉄朗',array['Tetsuro Kuroo']::text[],6),
  ('アニメ','ハイキュー!!','及川徹',array['Toru Oikawa']::text[],7),
  ('アニメ','ハイキュー!!','岩泉一',array['Hajime Iwaizumi']::text[],8),
  ('アニメ','ハイキュー!!','木兎光太郎',array['Kotaro Bokuto']::text[],9),
  ('アニメ','ハイキュー!!','赤葦京治',array['Keiji Akaashi']::text[],10),
  ('アニメ','ハイキュー!!','宮侑',array['Atsumu Miya']::text[],11),
  ('アニメ','ハイキュー!!','宮治',array['Osamu Miya']::text[],12),
  ('アニメ','僕のヒーローアカデミア','緑谷出久',array['Izuku Midoriya','Deku','デク']::text[],1),
  ('アニメ','僕のヒーローアカデミア','爆豪勝己',array['Katsuki Bakugo']::text[],2),
  ('アニメ','僕のヒーローアカデミア','轟焦凍',array['Shoto Todoroki']::text[],3),
  ('アニメ','僕のヒーローアカデミア','麗日お茶子',array['Ochaco Uraraka']::text[],4),
  ('アニメ','僕のヒーローアカデミア','飯田天哉',array['Tenya Iida']::text[],5),
  ('アニメ','僕のヒーローアカデミア','切島鋭児郎',array['Eijiro Kirishima']::text[],6),
  ('アニメ','僕のヒーローアカデミア','相澤消太',array['Shota Aizawa','Eraser Head']::text[],7),
  ('アニメ','僕のヒーローアカデミア','ホークス',array['Hawks','Keigo Takami']::text[],8),
  ('アニメ','僕のヒーローアカデミア','荼毘',array['Dabi']::text[],9),
  ('アニメ','僕のヒーローアカデミア','トガヒミコ',array['Himiko Toga']::text[],10),
  ('アニメ','チェンソーマン','デンジ',array['Denji']::text[],1),
  ('アニメ','チェンソーマン','ポチタ',array['Pochita']::text[],2),
  ('アニメ','チェンソーマン','マキマ',array['Makima']::text[],3),
  ('アニメ','チェンソーマン','パワー',array['Power']::text[],4),
  ('アニメ','チェンソーマン','早川アキ',array['Aki Hayakawa']::text[],5),
  ('アニメ','チェンソーマン','姫野',array['Himeno']::text[],6),
  ('アニメ','チェンソーマン','東山コベニ',array['Kobeni Higashiyama']::text[],7),
  ('アニメ','チェンソーマン','レゼ',array['Reze']::text[],8),
  ('アニメ','ダンダダン','綾瀬桃',array['Momo Ayase','モモ']::text[],1),
  ('アニメ','ダンダダン','オカルン',array['Okarun','高倉健']::text[],2),
  ('アニメ','ダンダダン','白鳥愛羅',array['Aira Shiratori','アイラ']::text[],3),
  ('アニメ','ダンダダン','円城寺仁',array['Jiji','ジジ']::text[],4),
  ('アニメ','ダンダダン','ターボババア',array['Turbo Granny']::text[],5),
  ('アニメ','ダンダダン','綾瀬星子',array['Seiko Ayase']::text[],6),
  ('アニメ','葬送のフリーレン','フリーレン',array['Frieren']::text[],1),
  ('アニメ','葬送のフリーレン','フェルン',array['Fern']::text[],2),
  ('アニメ','葬送のフリーレン','シュタルク',array['Stark']::text[],3),
  ('アニメ','葬送のフリーレン','ヒンメル',array['Himmel']::text[],4),
  ('アニメ','葬送のフリーレン','ハイター',array['Heiter']::text[],5),
  ('アニメ','葬送のフリーレン','アイゼン',array['Eisen']::text[],6),
  ('アニメ','葬送のフリーレン','ユーベル',array['Ubel','Übel']::text[],7),
  ('アニメ','葬送のフリーレン','ラント',array['Land']::text[],8),
  ('アニメ','WIND BREAKER','桜遥',array['Haruka Sakura']::text[],1),
  ('アニメ','WIND BREAKER','蘇枋隼飛',array['Hayato Suo']::text[],2),
  ('アニメ','WIND BREAKER','楡井秋彦',array['Akihiko Nirei']::text[],3),
  ('アニメ','WIND BREAKER','杉下京太郎',array['Kyotaro Sugishita']::text[],4),
  ('アニメ','WIND BREAKER','梅宮一',array['Hajime Umemiya']::text[],5),
  ('アニメ','WIND BREAKER','梶蓮',array['Ren Kaji']::text[],6),
  ('アニメ','WIND BREAKER','十亀条',array['Jo Togame']::text[],7),
  ('アニメ','WIND BREAKER','兎耳山丁子',array['Choji Tomiyama']::text[],8),
  ('アニメ','東京リベンジャーズ','花垣武道',array['Takemichi Hanagaki']::text[],1),
  ('アニメ','東京リベンジャーズ','佐野万次郎',array['Manjiro Sano','Mikey','マイキー']::text[],2),
  ('アニメ','東京リベンジャーズ','龍宮寺堅',array['Ken Ryuguji','Draken','ドラケン']::text[],3),
  ('アニメ','東京リベンジャーズ','松野千冬',array['Chifuyu Matsuno']::text[],4),
  ('アニメ','東京リベンジャーズ','場地圭介',array['Keisuke Baji']::text[],5),
  ('アニメ','東京リベンジャーズ','羽宮一虎',array['Kazutora Hanemiya']::text[],6),
  ('アニメ','東京リベンジャーズ','三ツ谷隆',array['Takashi Mitsuya']::text[],7),
  ('アニメ','東京リベンジャーズ','灰谷蘭',array['Ran Haitani']::text[],8),
  ('アニメ','東京リベンジャーズ','灰谷竜胆',array['Rindo Haitani']::text[],9),
  ('アニメ','【推しの子】','星野アイ',array['Ai Hoshino']::text[],1),
  ('アニメ','【推しの子】','星野アクア',array['Aqua Hoshino']::text[],2),
  ('アニメ','【推しの子】','星野ルビー',array['Ruby Hoshino']::text[],3),
  ('アニメ','【推しの子】','有馬かな',array['Kana Arima']::text[],4),
  ('アニメ','【推しの子】','黒川あかね',array['Akane Kurokawa']::text[],5),
  ('アニメ','【推しの子】','MEMちょ',array['MEMcho','MEM-cho']::text[],6),
  -- Game / mixed-media characters
  ('ゲーム','プロジェクトセカイ','初音ミク',array['Hatsune Miku','Miku']::text[],1),
  ('ゲーム','プロジェクトセカイ','鏡音リン',array['Kagamine Rin','Rin']::text[],2),
  ('ゲーム','プロジェクトセカイ','鏡音レン',array['Kagamine Len','Len']::text[],3),
  ('ゲーム','プロジェクトセカイ','巡音ルカ',array['Megurine Luka','Luka']::text[],4),
  ('ゲーム','プロジェクトセカイ','MEIKO',array['メイコ']::text[],5),
  ('ゲーム','プロジェクトセカイ','KAITO',array['カイト']::text[],6),
  ('ゲーム','プロジェクトセカイ','星乃一歌',array['Ichika Hoshino']::text[],7),
  ('ゲーム','プロジェクトセカイ','天馬咲希',array['Saki Tenma']::text[],8),
  ('ゲーム','プロジェクトセカイ','望月穂波',array['Honami Mochizuki']::text[],9),
  ('ゲーム','プロジェクトセカイ','日野森志歩',array['Shiho Hinomori']::text[],10),
  ('ゲーム','プロジェクトセカイ','花里みのり',array['Minori Hanasato']::text[],11),
  ('ゲーム','プロジェクトセカイ','桐谷遥',array['Haruka Kiritani']::text[],12),
  ('ゲーム','プロジェクトセカイ','桃井愛莉',array['Airi Momoi']::text[],13),
  ('ゲーム','プロジェクトセカイ','日野森雫',array['Shizuku Hinomori']::text[],14),
  ('ゲーム','プロジェクトセカイ','小豆沢こはね',array['Kohane Azusawa']::text[],15),
  ('ゲーム','プロジェクトセカイ','白石杏',array['An Shiraishi']::text[],16),
  ('ゲーム','プロジェクトセカイ','東雲彰人',array['Akito Shinonome']::text[],17),
  ('ゲーム','プロジェクトセカイ','青柳冬弥',array['Toya Aoyagi']::text[],18),
  ('ゲーム','プロジェクトセカイ','天馬司',array['Tsukasa Tenma']::text[],19),
  ('ゲーム','プロジェクトセカイ','鳳えむ',array['Emu Otori']::text[],20),
  ('ゲーム','プロジェクトセカイ','草薙寧々',array['Nene Kusanagi']::text[],21),
  ('ゲーム','プロジェクトセカイ','神代類',array['Rui Kamishiro']::text[],22),
  ('ゲーム','プロジェクトセカイ','宵崎奏',array['Kanade Yoisaki']::text[],23),
  ('ゲーム','プロジェクトセカイ','朝比奈まふゆ',array['Mafuyu Asahina']::text[],24),
  ('ゲーム','プロジェクトセカイ','東雲絵名',array['Ena Shinonome']::text[],25),
  ('ゲーム','プロジェクトセカイ','暁山瑞希',array['Mizuki Akiyama']::text[],26),
  ('ゲーム','ディズニー ツイステッドワンダーランド','リドル・ローズハート',array['Riddle Rosehearts','リドル']::text[],1),
  ('ゲーム','ディズニー ツイステッドワンダーランド','エース・トラッポラ',array['Ace Trappola','エース']::text[],2),
  ('ゲーム','ディズニー ツイステッドワンダーランド','デュース・スペード',array['Deuce Spade','デュース']::text[],3),
  ('ゲーム','ディズニー ツイステッドワンダーランド','レオナ・キングスカラー',array['Leona Kingscholar','レオナ']::text[],4),
  ('ゲーム','ディズニー ツイステッドワンダーランド','ラギー・ブッチ',array['Ruggie Bucchi','ラギー']::text[],5),
  ('ゲーム','ディズニー ツイステッドワンダーランド','ジャック・ハウル',array['Jack Howl','ジャック']::text[],6),
  ('ゲーム','ディズニー ツイステッドワンダーランド','アズール・アーシェングロット',array['Azul Ashengrotto','アズール']::text[],7),
  ('ゲーム','ディズニー ツイステッドワンダーランド','ジェイド・リーチ',array['Jade Leech','ジェイド']::text[],8),
  ('ゲーム','ディズニー ツイステッドワンダーランド','フロイド・リーチ',array['Floyd Leech','フロイド']::text[],9),
  ('ゲーム','ディズニー ツイステッドワンダーランド','カリム・アルアジーム',array['Kalim Al-Asim','カリム']::text[],10),
  ('ゲーム','ディズニー ツイステッドワンダーランド','ジャミル・バイパー',array['Jamil Viper','ジャミル']::text[],11),
  ('ゲーム','ディズニー ツイステッドワンダーランド','ヴィル・シェーンハイト',array['Vil Schoenheit','ヴィル']::text[],12),
  ('ゲーム','ディズニー ツイステッドワンダーランド','イデア・シュラウド',array['Idia Shroud','イデア']::text[],13),
  ('ゲーム','ディズニー ツイステッドワンダーランド','マレウス・ドラコニア',array['Malleus Draconia','マレウス']::text[],14),
  ('ゲーム','ディズニー ツイステッドワンダーランド','リリア・ヴァンルージュ',array['Lilia Vanrouge','リリア']::text[],15),
  ('ゲーム','ディズニー ツイステッドワンダーランド','シルバー',array['Silver']::text[],16),
  ('ゲーム','あんさんぶるスターズ!!','氷鷹北斗',array['Hokuto Hidaka']::text[],1),
  ('ゲーム','あんさんぶるスターズ!!','明星スバル',array['Subaru Akehoshi']::text[],2),
  ('ゲーム','あんさんぶるスターズ!!','遊木真',array['Makoto Yuki']::text[],3),
  ('ゲーム','あんさんぶるスターズ!!','衣更真緒',array['Mao Isara']::text[],4),
  ('ゲーム','あんさんぶるスターズ!!','天祥院英智',array['Eichi Tenshouin']::text[],5),
  ('ゲーム','あんさんぶるスターズ!!','日々樹渉',array['Wataru Hibiki']::text[],6),
  ('ゲーム','あんさんぶるスターズ!!','姫宮桃李',array['Tori Himemiya']::text[],7),
  ('ゲーム','あんさんぶるスターズ!!','朔間零',array['Rei Sakuma']::text[],8),
  ('ゲーム','あんさんぶるスターズ!!','羽風薫',array['Kaoru Hakaze']::text[],9),
  ('ゲーム','あんさんぶるスターズ!!','大神晃牙',array['Koga Oogami']::text[],10),
  ('ゲーム','あんさんぶるスターズ!!','朱桜司',array['Tsukasa Suou']::text[],11),
  ('ゲーム','あんさんぶるスターズ!!','月永レオ',array['Leo Tsukinaga']::text[],12),
  ('ゲーム','あんさんぶるスターズ!!','瀬名泉',array['Izumi Sena']::text[],13),
  ('ゲーム','あんさんぶるスターズ!!','朔間凛月',array['Ritsu Sakuma']::text[],14),
  ('ゲーム','あんさんぶるスターズ!!','鳴上嵐',array['Arashi Narukami']::text[],15),
  ('ゲーム','あんさんぶるスターズ!!','天城一彩',array['Hiiro Amagi']::text[],16),
  ('ゲーム','あんさんぶるスターズ!!','白鳥藍良',array['Aira Shiratori']::text[],17),
  ('ゲーム','あんさんぶるスターズ!!','礼瀬マヨイ',array['Mayoi Ayase']::text[],18),
  ('ゲーム','あんさんぶるスターズ!!','風早巽',array['Tatsumi Kazehaya']::text[],19),
  ('ゲーム','あんさんぶるスターズ!!','天城燐音',array['Rinne Amagi']::text[],20),
  ('ゲーム','あんさんぶるスターズ!!','HiMERU',array['ヒメル']::text[],21),
  ('ゲーム','あんさんぶるスターズ!!','桜河こはく',array['Kohaku Oukawa']::text[],22),
  ('ゲーム','あんさんぶるスターズ!!','椎名ニキ',array['Niki Shiina']::text[],23),
  ('ゲーム','あんさんぶるスターズ!!','乱凪砂',array['Nagisa Ran']::text[],24),
  ('ゲーム','あんさんぶるスターズ!!','巴日和',array['Hiyori Tomoe']::text[],25),
  ('ゲーム','あんさんぶるスターズ!!','七種茨',array['Ibara Saegusa']::text[],26),
  ('ゲーム','あんさんぶるスターズ!!','漣ジュン',array['Jun Sazanami']::text[],27);

insert into public.characters_master (group_id, genre_id, name, aliases, display_order)
select
  gm.id,
  ge.id,
  sc.name,
  sc.aliases,
  sc.display_order
from _ihub_seed_characters sc
join public.genres_master ge on ge.name = sc.genre_name
join public.groups_master gm on gm.genre_id = ge.id and gm.name = sc.group_name
where not exists (
  select 1
    from public.characters_master c
   where c.group_id = gm.id
     and c.name = sc.name
);

-- =====================================================================
-- 完了
-- =====================================================================
