-- =====================================================================
-- iter168.20: 再整理後分類に沿った推しマスタ拡充
-- =====================================================================
-- 実在するグループ/作品/IP/チーム/人物だけを登録する。
-- L1 は groups_master、L2 は characters_master に入れ、
-- solo は groups_master.kind='solo' として扱う。

create temporary table _megrum_seed_groups (
  genre_name text not null,
  name text not null,
  aliases text[] not null default '{}',
  kind text not null,
  display_order integer not null
) on commit drop;

insert into _megrum_seed_groups (genre_name, name, aliases, kind, display_order) values
  -- K-POP男性
  ('K-POP男性', 'TWS', array['투어스']::text[], 'group', 30),
  ('K-POP男性', 'THE BOYZ', array['더보이즈', 'ドボイズ']::text[], 'group', 31),
  ('K-POP男性', 'NCT 127', array['엔시티 127']::text[], 'group', 32),
  ('K-POP男性', 'NCT DREAM', array['엔시티 드림']::text[], 'group', 33),
  ('K-POP男性', 'EXO', array['엑소']::text[], 'group', 34),
  ('K-POP男性', 'SHINee', array['샤이니']::text[], 'group', 35),
  ('K-POP男性', 'MONSTA X', array['몬스타엑스']::text[], 'group', 36),
  ('K-POP男性', 'xikers', array['싸이커스']::text[], 'group', 37),
  -- K-POP女性
  ('K-POP女性', 'BLACKPINK', array['블랙핑크', 'ブラピン']::text[], 'group', 30),
  ('K-POP女性', 'Red Velvet', array['레드벨벳', 'レドベル']::text[], 'group', 31),
  ('K-POP女性', 'ILLIT', array['아일릿', 'アイリット']::text[], 'group', 32),
  ('K-POP女性', 'KISS OF LIFE', array['키스오브라이프', 'キオプ']::text[], 'group', 33),
  ('K-POP女性', 'NiziU', array['ニジュー']::text[], 'group', 34),
  ('K-POP女性', 'STAYC', array['스테이씨']::text[], 'group', 35),
  ('K-POP女性', 'Kep1er', array['케플러', 'ケプラー']::text[], 'group', 36),
  ('K-POP女性', 'Billlie', array['빌리']::text[], 'group', 37),
  ('K-POP女性', 'tripleS', array['트리플에스']::text[], 'group', 38),
  -- 国内男性
  ('国内男性', 'Travis Japan', array['トラジャ']::text[], 'group', 30),
  ('国内男性', 'Aぇ! group', array['Aぇ group', 'Aぇ']::text[], 'group', 31),
  ('国内男性', 'timelesz', array['タイムレス', 'Sexy Zone']::text[], 'group', 32),
  ('国内男性', 'WEST.', array['WEST', 'ジャニーズWEST']::text[], 'group', 33),
  ('国内男性', 'M!LK', array['ミルク']::text[], 'group', 34),
  ('国内男性', '超特急', array['Bullet Train']::text[], 'group', 35),
  ('国内男性', 'THE RAMPAGE', array['THE RAMPAGE from EXILE TRIBE']::text[], 'group', 36),
  ('国内男性', 'FANTASTICS', array['FANTASTICS from EXILE TRIBE']::text[], 'group', 37),
  ('国内男性', 'GENERATIONS', array['GENERATIONS from EXILE TRIBE']::text[], 'group', 38),
  ('国内男性', 'IMP.', array['IMP']::text[], 'group', 39),
  -- 国内女性
  ('国内女性', 'AKB48', array[]::text[], 'group', 30),
  ('国内女性', 'SKE48', array[]::text[], 'group', 31),
  ('国内女性', 'NMB48', array[]::text[], 'group', 32),
  ('国内女性', 'HKT48', array[]::text[], 'group', 33),
  ('国内女性', 'STU48', array[]::text[], 'group', 34),
  ('国内女性', 'ももいろクローバーZ', array['ももクロ']::text[], 'group', 35),
  ('国内女性', '私立恵比寿中学', array['エビ中']::text[], 'group', 36),
  ('国内女性', 'CANDY TUNE', array['キャンディーチューン']::text[], 'group', 37),
  ('国内女性', 'CUTIE STREET', array['きゅーすと']::text[], 'group', 38),
  ('国内女性', '高嶺のなでしこ', array['たかねこ']::text[], 'group', 39),
  ('国内女性', 'iLiFE!', array['アイライフ']::text[], 'group', 40),
  ('国内女性', 'モーニング娘。', array['モーニング娘', 'モー娘。']::text[], 'group', 41),
  -- 歌い手
  ('歌い手', 'AMPTAKxCOLORS', array['AMPTAK', 'アンプタック']::text[], 'group', 20),
  ('歌い手', 'ちょこらび', array['チョコレートラビッツ']::text[], 'group', 21),
  ('歌い手', 'めろんぱーかー', array['めろぱか']::text[], 'group', 22),
  ('歌い手', '天月', array['天月-あまつき-', 'Amatsuki']::text[], 'solo', 23),
  ('歌い手', 'Gero', array[]::text[], 'solo', 24),
  ('歌い手', 'luz', array[]::text[], 'solo', 25),
  ('歌い手', 'nqrse', array['なるせ']::text[], 'solo', 26),
  ('歌い手', '96猫', array['Kuroneko']::text[], 'solo', 27),
  -- 声優
  ('声優', '梶裕貴', array['Yuki Kaji']::text[], 'solo', 20),
  ('声優', '下野紘', array['Hiro Shimono']::text[], 'solo', 21),
  ('声優', '神谷浩史', array['Hiroshi Kamiya']::text[], 'solo', 22),
  ('声優', '花江夏樹', array['Natsuki Hanae']::text[], 'solo', 23),
  ('声優', '斉藤壮馬', array['Soma Saito']::text[], 'solo', 24),
  ('声優', '鬼頭明里', array['Akari Kito']::text[], 'solo', 25),
  ('声優', '早見沙織', array['Saori Hayami']::text[], 'solo', 26),
  ('声優', '悠木碧', array['Aoi Yuki']::text[], 'solo', 27),
  ('声優', '津田健次郎', array['Kenjiro Tsuda']::text[], 'solo', 28),
  ('声優', '木村良平', array['Ryohei Kimura']::text[], 'solo', 29),
  ('声優', '増田俊樹', array['Toshiki Masuda']::text[], 'solo', 30),
  -- 2.5次元・舞台
  ('2.5次元・舞台', 'ミュージカル「テニスの王子様」', array['テニミュ']::text[], 'work', 20),
  ('2.5次元・舞台', '舞台「刀剣乱舞」', array['刀ステ']::text[], 'work', 21),
  ('2.5次元・舞台', 'ミュージカル「刀剣乱舞」', array['刀ミュ']::text[], 'work', 22),
  ('2.5次元・舞台', '荒牧慶彦', array['Yoshihiko Aramaki']::text[], 'solo', 40),
  ('2.5次元・舞台', '和田雅成', array['Masanari Wada']::text[], 'solo', 41),
  ('2.5次元・舞台', '佐藤流司', array['Ryuji Sato']::text[], 'solo', 42),
  ('2.5次元・舞台', '黒羽麻璃央', array['Mario Kuroba']::text[], 'solo', 43),
  ('2.5次元・舞台', '植田圭輔', array['Keisuke Ueda']::text[], 'solo', 44),
  ('2.5次元・舞台', '高橋健介', array['Kensuke Takahashi']::text[], 'solo', 45),
  ('2.5次元・舞台', '北村諒', array['Ryo Kitamura']::text[], 'solo', 46),
  ('2.5次元・舞台', '立石俊樹', array['Toshiki Tateishi']::text[], 'solo', 47),
  ('2.5次元・舞台', '岡宮来夢', array['Kurumu Okamiya']::text[], 'solo', 48),
  ('2.5次元・舞台', '笹森裕貴', array['Hiroki Sasamori']::text[], 'solo', 49),
  -- アニメ・マンガ
  ('アニメ・マンガ', 'ONE PIECE', array['ワンピース']::text[], 'work', 30),
  ('アニメ・マンガ', '名探偵コナン', array['Detective Conan']::text[], 'work', 31),
  ('アニメ・マンガ', 'SPY×FAMILY', array['SPY FAMILY', 'スパイファミリー']::text[], 'work', 32),
  ('アニメ・マンガ', '進撃の巨人', array['Attack on Titan']::text[], 'work', 33),
  ('アニメ・マンガ', '銀魂', array['Gintama']::text[], 'work', 34),
  ('アニメ・マンガ', '文豪ストレイドッグス', array['文スト', 'Bungo Stray Dogs']::text[], 'work', 35),
  ('アニメ・マンガ', '黒執事', array['Black Butler']::text[], 'work', 36),
  ('アニメ・マンガ', 'Free!', array['Free! - Iwatobi Swim Club']::text[], 'work', 37),
  ('アニメ・マンガ', '黒子のバスケ', array['黒バス', 'Kuroko''s Basketball']::text[], 'work', 38),
  ('アニメ・マンガ', 'テニスの王子様', array['テニプリ', 'The Prince of Tennis']::text[], 'work', 39),
  -- ゲーム
  ('ゲーム', '原神', array['Genshin Impact']::text[], 'work', 30),
  ('ゲーム', '崩壊:スターレイル', array['Honkai: Star Rail', 'スタレ']::text[], 'work', 31),
  ('ゲーム', 'ゼンレスゾーンゼロ', array['Zenless Zone Zero', 'ZZZ']::text[], 'work', 32),
  ('ゲーム', 'Fate/Grand Order', array['FGO']::text[], 'work', 33),
  ('ゲーム', 'アークナイツ', array['Arknights']::text[], 'work', 34),
  ('ゲーム', 'アイドルマスター シンデレラガールズ', array['デレマス']::text[], 'work', 35),
  ('ゲーム', 'アイドルマスター SideM', array['SideM']::text[], 'work', 36),
  ('ゲーム', 'ウマ娘 プリティーダービー', array['ウマ娘']::text[], 'work', 37),
  -- キャラクターIP
  ('キャラクターIP', 'サンリオキャラクターズ', array['Sanrio Characters', 'サンリオ']::text[], 'work', 1),
  ('キャラクターIP', 'ちいかわ', array['なんか小さくてかわいいやつ']::text[], 'work', 2),
  ('キャラクターIP', 'すみっコぐらし', array['Sumikkogurashi']::text[], 'work', 3),
  ('キャラクターIP', 'リラックマ', array['Rilakkuma']::text[], 'work', 4),
  ('キャラクターIP', 'ポケットモンスター', array['ポケモン', 'Pokemon']::text[], 'work', 5),
  ('キャラクターIP', '星のカービィ', array['Kirby']::text[], 'work', 6),
  ('キャラクターIP', 'ディズニー ミッキー&フレンズ', array['Mickey Mouse & Friends']::text[], 'work', 7),
  ('キャラクターIP', 'ミッフィー', array['Miffy', 'うさこちゃん']::text[], 'work', 8),
  ('キャラクターIP', 'PEANUTS', array['スヌーピー', 'Snoopy']::text[], 'work', 9),
  ('キャラクターIP', 'おぱんちゅうさぎ', array[]::text[], 'work', 10),
  ('キャラクターIP', 'mofusand', array['モフサンド']::text[], 'work', 11),
  ('キャラクターIP', 'パペットスンスン', array['PUPPET SUNSUN']::text[], 'work', 12),
  -- VTuber・配信者
  ('VTuber・配信者', 'にじさんじ', array['NIJISANJI']::text[], 'group', 1),
  ('VTuber・配信者', 'hololive', array['ホロライブ']::text[], 'group', 2),
  ('VTuber・配信者', 'ぶいすぽっ！', array['VSPO!']::text[], 'group', 3),
  ('VTuber・配信者', 'Neo-Porte', array['ネオポルテ']::text[], 'group', 4),
  ('VTuber・配信者', 'TOP4', array['ゲーム実況TOP4']::text[], 'group', 5),
  ('VTuber・配信者', '東海オンエア', array[]::text[], 'group', 6),
  ('VTuber・配信者', 'Fischer''s', array['フィッシャーズ']::text[], 'group', 7),
  ('VTuber・配信者', 'HIKAKIN', array['ヒカキン']::text[], 'solo', 20),
  ('VTuber・配信者', 'はじめしゃちょー', array[]::text[], 'solo', 21),
  -- お笑い
  ('お笑い', '令和ロマン', array[]::text[], 'group', 1),
  ('お笑い', '真空ジェシカ', array[]::text[], 'group', 2),
  ('お笑い', 'マユリカ', array[]::text[], 'group', 3),
  ('お笑い', 'ぱーてぃーちゃん', array[]::text[], 'group', 4),
  ('お笑い', 'バッテリィズ', array[]::text[], 'group', 5),
  ('お笑い', 'ヤーレンズ', array[]::text[], 'group', 6),
  ('お笑い', 'エバース', array[]::text[], 'group', 7),
  ('お笑い', 'ジョックロック', array[]::text[], 'group', 8),
  ('お笑い', 'ママタルト', array[]::text[], 'group', 9),
  ('お笑い', 'トム・ブラウン', array[]::text[], 'group', 10),
  ('お笑い', 'ダイタク', array[]::text[], 'group', 11),
  ('お笑い', 'ハナコ', array[]::text[], 'group', 12),
  ('お笑い', 'かまいたち', array[]::text[], 'group', 13),
  ('お笑い', '霜降り明星', array[]::text[], 'group', 14),
  ('お笑い', 'ニューヨーク', array[]::text[], 'group', 15),
  ('お笑い', '男性ブランコ', array[]::text[], 'group', 16),
  -- スポーツ
  ('スポーツ', '野球日本代表 侍ジャパン', array['侍ジャパン', 'SAMURAI JAPAN']::text[], 'group', 1),
  ('スポーツ', 'サッカー日本代表 SAMURAI BLUE', array['SAMURAI BLUE', 'サムライブルー']::text[], 'group', 2),
  ('スポーツ', 'バスケットボール日本代表 AKATSUKI JAPAN', array['AKATSUKI JAPAN']::text[], 'group', 3),
  ('スポーツ', '阪神タイガース', array[]::text[], 'group', 20),
  ('スポーツ', '読売ジャイアンツ', array['巨人']::text[], 'group', 21),
  ('スポーツ', '東京ヤクルトスワローズ', array['ヤクルト']::text[], 'group', 22),
  ('スポーツ', 'オリックス・バファローズ', array['オリックス']::text[], 'group', 23),
  ('スポーツ', '北海道日本ハムファイターズ', array['日本ハム']::text[], 'group', 24),
  ('スポーツ', '福岡ソフトバンクホークス', array['ソフトバンク']::text[], 'group', 25),
  ('スポーツ', '浦和レッズ', array[]::text[], 'group', 40),
  ('スポーツ', '鹿島アントラーズ', array[]::text[], 'group', 41),
  ('スポーツ', '横浜F・マリノス', array[]::text[], 'group', 42),
  ('スポーツ', '川崎フロンターレ', array[]::text[], 'group', 43),
  ('スポーツ', 'ヴィッセル神戸', array[]::text[], 'group', 44),
  ('スポーツ', '千葉ジェッツ', array[]::text[], 'group', 60),
  ('スポーツ', '宇都宮ブレックス', array[]::text[], 'group', 61),
  ('スポーツ', 'アルバルク東京', array[]::text[], 'group', 62),
  ('スポーツ', '琉球ゴールデンキングス', array[]::text[], 'group', 63),
  ('スポーツ', '横浜ビー・コルセアーズ', array[]::text[], 'group', 64),
  -- 俳優・タレント
  ('俳優・タレント', '高橋文哉', array['Fumiya Takahashi']::text[], 'solo', 1),
  ('俳優・タレント', '山田裕貴', array['Yuki Yamada']::text[], 'solo', 2),
  ('俳優・タレント', '吉沢亮', array['Ryo Yoshizawa']::text[], 'solo', 3),
  ('俳優・タレント', '横浜流星', array['Ryusei Yokohama']::text[], 'solo', 4),
  ('俳優・タレント', '北村匠海', array['Takumi Kitamura']::text[], 'solo', 5),
  ('俳優・タレント', '赤楚衛二', array['Eiji Akaso']::text[], 'solo', 6),
  ('俳優・タレント', '志尊淳', array['Jun Shison']::text[], 'solo', 7),
  ('俳優・タレント', '萩原利久', array['Riku Hagiwara']::text[], 'solo', 8),
  ('俳優・タレント', '八木勇征', array['Yusei Yagi']::text[], 'solo', 9),
  ('俳優・タレント', '浜辺美波', array['Minami Hamabe']::text[], 'solo', 20),
  ('俳優・タレント', '今田美桜', array['Mio Imada']::text[], 'solo', 21),
  ('俳優・タレント', '橋本環奈', array['Kanna Hashimoto']::text[], 'solo', 22),
  ('俳優・タレント', '広瀬すず', array['Suzu Hirose']::text[], 'solo', 23),
  ('俳優・タレント', '永野芽郁', array['Mei Nagano']::text[], 'solo', 24),
  ('俳優・タレント', '杉咲花', array['Hana Sugisaki']::text[], 'solo', 25),
  ('俳優・タレント', '清原果耶', array['Kaya Kiyohara']::text[], 'solo', 26),
  -- 海外エンタメ
  ('海外エンタメ', 'パク・ソジュン', array['Park Seo-jun', '박서준']::text[], 'solo', 1),
  ('海外エンタメ', 'キム・スヒョン', array['Kim Soo-hyun', '김수현']::text[], 'solo', 2),
  ('海外エンタメ', 'ソン・ガン', array['Song Kang', '송강']::text[], 'solo', 3),
  ('海外エンタメ', 'チャ・ウヌ', array['Cha Eun-woo', '차은우']::text[], 'solo', 4),
  ('海外エンタメ', 'イ・ミンホ', array['Lee Min-ho', '이민호']::text[], 'solo', 5),
  ('海外エンタメ', 'コン・ユ', array['Gong Yoo', '공유']::text[], 'solo', 6),
  ('海外エンタメ', 'チョン・ヘイン', array['Jung Hae-in', '정해인']::text[], 'solo', 7),
  ('海外エンタメ', 'ピョン・ウソク', array['Byeon Woo-seok', '변우석']::text[], 'solo', 8),
  ('海外エンタメ', 'パク・ボゴム', array['Park Bo-gum', '박보검']::text[], 'solo', 9),
  ('海外エンタメ', 'キム・ジウォン', array['Kim Ji-won', '김지원']::text[], 'solo', 20),
  ('海外エンタメ', 'ペ・スジ', array['Bae Suzy', '수지']::text[], 'solo', 21),
  ('海外エンタメ', 'IU', array['アイユー', 'イ・ジウン', 'Lee Ji-eun', '이지은']::text[], 'solo', 22),
  ('海外エンタメ', 'ハン・ソヒ', array['Han So-hee', '한소희']::text[], 'solo', 23),
  ('海外エンタメ', 'キム・セジョン', array['Kim Se-jeong', '김세정']::text[], 'solo', 24),
  ('海外エンタメ', 'Bright Vachirawit', array['ブライト', 'วชิรวิชญ์ ชีวอารี']::text[], 'solo', 40),
  ('海外エンタメ', 'Win Metawin', array['ウィン', 'เมธวิน โอภาสเอี่ยมขจร']::text[], 'solo', 41),
  ('海外エンタメ', 'Gemini Norawit', array['ジェミナイ', 'นรวิชญ์ ฐิติเจริญรักษ์']::text[], 'solo', 42),
  ('海外エンタメ', 'Fourth Nattawat', array['フォース', 'ณัฐวรรธน์ จิโรชน์ธิกุล']::text[], 'solo', 43),
  ('海外エンタメ', 'Pond Naravit', array['ポンド', 'ณราวิชญ์ เลิศรัตน์โกสุมภ์']::text[], 'solo', 44),
  ('海外エンタメ', 'Phuwin Tangsakyuen', array['プーウィン', 'ภูวินทร์ ตั้งศักดิ์ยืน']::text[], 'solo', 45);

insert into public.groups_master (genre_id, name, aliases, kind, display_order)
select
  ge.id,
  sg.name,
  sg.aliases,
  sg.kind,
  sg.display_order
from _megrum_seed_groups sg
join public.genres_master ge on ge.name = sg.genre_name
on conflict (genre_id, name) do update
  set aliases = excluded.aliases,
      kind = excluded.kind,
      display_order = excluded.display_order;

create temporary table _megrum_seed_characters (
  genre_name text not null,
  group_name text not null,
  name text not null,
  aliases text[] not null default '{}',
  display_order integer not null
) on commit drop;

insert into _megrum_seed_characters (genre_name, group_name, name, aliases, display_order) values
  -- K-POP男性 members
  ('K-POP男性','TWS','シニュ',array['SHINYU','신유']::text[],1),
  ('K-POP男性','TWS','ドフン',array['DOHOON','도훈']::text[],2),
  ('K-POP男性','TWS','ヨンジェ',array['YOUNGJAE','영재']::text[],3),
  ('K-POP男性','TWS','ハンジン',array['HANJIN','한진']::text[],4),
  ('K-POP男性','TWS','ジフン',array['JIHOON','지훈']::text[],5),
  ('K-POP男性','TWS','ギョンミン',array['KYUNGMIN','경민']::text[],6),
  ('K-POP男性','NCT DREAM','マーク',array['MARK','마크']::text[],1),
  ('K-POP男性','NCT DREAM','ロンジュン',array['RENJUN','런쥔']::text[],2),
  ('K-POP男性','NCT DREAM','ジェノ',array['JENO','제노']::text[],3),
  ('K-POP男性','NCT DREAM','ヘチャン',array['HAECHAN','해찬']::text[],4),
  ('K-POP男性','NCT DREAM','ジェミン',array['JAEMIN','재민']::text[],5),
  ('K-POP男性','NCT DREAM','チョンロ',array['CHENLE','천러']::text[],6),
  ('K-POP男性','NCT DREAM','チソン',array['JISUNG','지성']::text[],7),
  ('K-POP男性','EXO','シウミン',array['XIUMIN','시우민']::text[],1),
  ('K-POP男性','EXO','スホ',array['SUHO','수호']::text[],2),
  ('K-POP男性','EXO','ベクヒョン',array['BAEKHYUN','백현']::text[],3),
  ('K-POP男性','EXO','チェン',array['CHEN','첸']::text[],4),
  ('K-POP男性','EXO','チャンヨル',array['CHANYEOL','찬열']::text[],5),
  ('K-POP男性','EXO','ディオ',array['D.O.','디오']::text[],6),
  ('K-POP男性','EXO','カイ',array['KAI','카이']::text[],7),
  ('K-POP男性','EXO','セフン',array['SEHUN','세훈']::text[],8),
  -- K-POP女性 members
  ('K-POP女性','BLACKPINK','ジス',array['JISOO','지수']::text[],1),
  ('K-POP女性','BLACKPINK','ジェニー',array['JENNIE','제니']::text[],2),
  ('K-POP女性','BLACKPINK','ロゼ',array['ROSÉ','ROSE','로제']::text[],3),
  ('K-POP女性','BLACKPINK','リサ',array['LISA','리사']::text[],4),
  ('K-POP女性','Red Velvet','アイリーン',array['IRENE','아이린']::text[],1),
  ('K-POP女性','Red Velvet','スルギ',array['SEULGI','슬기']::text[],2),
  ('K-POP女性','Red Velvet','ウェンディ',array['WENDY','웬디']::text[],3),
  ('K-POP女性','Red Velvet','ジョイ',array['JOY','조이']::text[],4),
  ('K-POP女性','Red Velvet','イェリ',array['YERI','예리']::text[],5),
  ('K-POP女性','ILLIT','ユナ',array['YUNAH','윤아']::text[],1),
  ('K-POP女性','ILLIT','ミンジュ',array['MINJU','민주']::text[],2),
  ('K-POP女性','ILLIT','モカ',array['MOKA','모카']::text[],3),
  ('K-POP女性','ILLIT','ウォンヒ',array['WONHEE','원희']::text[],4),
  ('K-POP女性','ILLIT','イロハ',array['IROHA','이로하']::text[],5),
  ('K-POP女性','KISS OF LIFE','ジュリー',array['JULIE','쥴리']::text[],1),
  ('K-POP女性','KISS OF LIFE','ナッティ',array['NATTY','나띠']::text[],2),
  ('K-POP女性','KISS OF LIFE','ベル',array['BELLE','벨']::text[],3),
  ('K-POP女性','KISS OF LIFE','ハヌル',array['HANEUL','하늘']::text[],4),
  ('K-POP女性','NiziU','マコ',array['MAKO']::text[],1),
  ('K-POP女性','NiziU','リオ',array['RIO']::text[],2),
  ('K-POP女性','NiziU','マヤ',array['MAYA']::text[],3),
  ('K-POP女性','NiziU','リク',array['RIKU']::text[],4),
  ('K-POP女性','NiziU','アヤカ',array['AYAKA']::text[],5),
  ('K-POP女性','NiziU','マユカ',array['MAYUKA']::text[],6),
  ('K-POP女性','NiziU','リマ',array['RIMA']::text[],7),
  ('K-POP女性','NiziU','ミイヒ',array['MIIHI']::text[],8),
  ('K-POP女性','NiziU','ニナ',array['NINA']::text[],9),
  -- 国内男性 members
  ('国内男性','Travis Japan','宮近海斗',array['Kaito Miyachika']::text[],1),
  ('国内男性','Travis Japan','中村海人',array['Kaito Nakamura']::text[],2),
  ('国内男性','Travis Japan','七五三掛龍也',array['Ryuya Shimekake']::text[],3),
  ('国内男性','Travis Japan','川島如恵留',array['Noel Kawashima']::text[],4),
  ('国内男性','Travis Japan','吉澤閑也',array['Shizuya Yoshizawa']::text[],5),
  ('国内男性','Travis Japan','松田元太',array['Genta Matsuda']::text[],6),
  ('国内男性','Travis Japan','松倉海斗',array['Kaito Matsukura']::text[],7),
  ('国内男性','Aぇ! group','正門良規',array['Yoshinori Masakado']::text[],1),
  ('国内男性','Aぇ! group','末澤誠也',array['Seiya Suezawa']::text[],2),
  ('国内男性','Aぇ! group','草間リチャード敬太',array['Richard Keita Kusama']::text[],3),
  ('国内男性','Aぇ! group','小島健',array['Ken Kojima']::text[],4),
  ('国内男性','Aぇ! group','佐野晶哉',array['Masaya Sano']::text[],5),
  ('国内男性','timelesz','佐藤勝利',array['Shori Sato']::text[],1),
  ('国内男性','timelesz','菊池風磨',array['Fuma Kikuchi']::text[],2),
  ('国内男性','timelesz','松島聡',array['So Matsushima']::text[],3),
  ('国内男性','timelesz','寺西拓人',array['Takuto Teranishi']::text[],4),
  ('国内男性','timelesz','原嘉孝',array['Yoshitaka Hara']::text[],5),
  ('国内男性','timelesz','橋本将生',array['Masaki Hashimoto']::text[],6),
  ('国内男性','timelesz','猪俣周杜',array['Shuto Inomata']::text[],7),
  ('国内男性','timelesz','篠塚大輝',array['Taiki Shinozuka']::text[],8),
  -- 国内女性 members
  ('国内女性','CANDY TUNE','立花琴未',array['Kotomi Tachibana']::text[],1),
  ('国内女性','CANDY TUNE','小川奈々子',array['Nanako Ogawa']::text[],2),
  ('国内女性','CANDY TUNE','桐原美月',array['Mizuki Kirihara']::text[],3),
  ('国内女性','CANDY TUNE','福山梨乃',array['Rino Fukuyama']::text[],4),
  ('国内女性','CANDY TUNE','南なつ',array['Natsu Minami']::text[],5),
  ('国内女性','CANDY TUNE','宮野静',array['Shizuka Miyano']::text[],6),
  ('国内女性','CANDY TUNE','村川緋杏',array['Bibian Murakawa']::text[],7),
  -- アニメ・マンガ characters
  ('アニメ・マンガ','ONE PIECE','モンキー・D・ルフィ',array['Luffy']::text[],1),
  ('アニメ・マンガ','ONE PIECE','ロロノア・ゾロ',array['Zoro']::text[],2),
  ('アニメ・マンガ','ONE PIECE','ナミ',array['Nami']::text[],3),
  ('アニメ・マンガ','ONE PIECE','サンジ',array['Sanji']::text[],4),
  ('アニメ・マンガ','ONE PIECE','トニートニー・チョッパー',array['Chopper']::text[],5),
  ('アニメ・マンガ','ONE PIECE','ポートガス・D・エース',array['Ace']::text[],6),
  ('アニメ・マンガ','ONE PIECE','トラファルガー・ロー',array['Law']::text[],7),
  ('アニメ・マンガ','ONE PIECE','シャンクス',array['Shanks']::text[],8),
  ('アニメ・マンガ','名探偵コナン','江戸川コナン',array['Conan Edogawa']::text[],1),
  ('アニメ・マンガ','名探偵コナン','工藤新一',array['Shinichi Kudo']::text[],2),
  ('アニメ・マンガ','名探偵コナン','毛利蘭',array['Ran Mouri']::text[],3),
  ('アニメ・マンガ','名探偵コナン','灰原哀',array['Ai Haibara']::text[],4),
  ('アニメ・マンガ','名探偵コナン','怪盗キッド',array['Kaito Kid']::text[],5),
  ('アニメ・マンガ','名探偵コナン','安室透',array['降谷零','Rei Furuya','Toru Amuro']::text[],6),
  ('アニメ・マンガ','名探偵コナン','赤井秀一',array['Shuichi Akai']::text[],7),
  ('アニメ・マンガ','SPY×FAMILY','ロイド・フォージャー',array['Loid Forger']::text[],1),
  ('アニメ・マンガ','SPY×FAMILY','ヨル・フォージャー',array['Yor Forger']::text[],2),
  ('アニメ・マンガ','SPY×FAMILY','アーニャ・フォージャー',array['Anya Forger']::text[],3),
  ('アニメ・マンガ','SPY×FAMILY','ボンド・フォージャー',array['Bond Forger']::text[],4),
  ('アニメ・マンガ','進撃の巨人','エレン・イェーガー',array['Eren Yeager']::text[],1),
  ('アニメ・マンガ','進撃の巨人','ミカサ・アッカーマン',array['Mikasa Ackerman']::text[],2),
  ('アニメ・マンガ','進撃の巨人','アルミン・アルレルト',array['Armin Arlert']::text[],3),
  ('アニメ・マンガ','進撃の巨人','リヴァイ',array['Levi']::text[],4),
  ('アニメ・マンガ','銀魂','坂田銀時',array['Gintoki Sakata']::text[],1),
  ('アニメ・マンガ','銀魂','志村新八',array['Shinpachi Shimura']::text[],2),
  ('アニメ・マンガ','銀魂','神楽',array['Kagura']::text[],3),
  ('アニメ・マンガ','銀魂','土方十四郎',array['Toshiro Hijikata']::text[],4),
  ('アニメ・マンガ','銀魂','沖田総悟',array['Sougo Okita']::text[],5),
  ('アニメ・マンガ','文豪ストレイドッグス','中島敦',array['Atsushi Nakajima']::text[],1),
  ('アニメ・マンガ','文豪ストレイドッグス','太宰治',array['Osamu Dazai']::text[],2),
  ('アニメ・マンガ','文豪ストレイドッグス','国木田独歩',array['Doppo Kunikida']::text[],3),
  ('アニメ・マンガ','文豪ストレイドッグス','江戸川乱歩',array['Ranpo Edogawa']::text[],4),
  ('アニメ・マンガ','文豪ストレイドッグス','中原中也',array['Chuya Nakahara']::text[],5),
  ('アニメ・マンガ','黒執事','セバスチャン・ミカエリス',array['Sebastian Michaelis']::text[],1),
  ('アニメ・マンガ','黒執事','シエル・ファントムハイヴ',array['Ciel Phantomhive']::text[],2),
  ('アニメ・マンガ','Free!','七瀬遙',array['Haruka Nanase']::text[],1),
  ('アニメ・マンガ','Free!','橘真琴',array['Makoto Tachibana']::text[],2),
  ('アニメ・マンガ','Free!','松岡凛',array['Rin Matsuoka']::text[],3),
  ('アニメ・マンガ','黒子のバスケ','黒子テツヤ',array['Tetsuya Kuroko']::text[],1),
  ('アニメ・マンガ','黒子のバスケ','火神大我',array['Taiga Kagami']::text[],2),
  ('アニメ・マンガ','黒子のバスケ','黄瀬涼太',array['Ryota Kise']::text[],3),
  ('アニメ・マンガ','黒子のバスケ','赤司征十郎',array['Seijuro Akashi']::text[],4),
  ('アニメ・マンガ','テニスの王子様','越前リョーマ',array['Ryoma Echizen']::text[],1),
  ('アニメ・マンガ','テニスの王子様','手塚国光',array['Kunimitsu Tezuka']::text[],2),
  ('アニメ・マンガ','テニスの王子様','跡部景吾',array['Keigo Atobe']::text[],3),
  ('アニメ・マンガ','テニスの王子様','不二周助',array['Shusuke Fuji']::text[],4),
  -- ゲーム characters
  ('ゲーム','原神','空',array['Aether']::text[],1),
  ('ゲーム','原神','蛍',array['Lumine']::text[],2),
  ('ゲーム','原神','パイモン',array['Paimon']::text[],3),
  ('ゲーム','原神','鍾離',array['Zhongli']::text[],4),
  ('ゲーム','原神','タルタリヤ',array['Childe','Tartaglia']::text[],5),
  ('ゲーム','原神','魈',array['Xiao']::text[],6),
  ('ゲーム','原神','雷電将軍',array['Raiden Shogun']::text[],7),
  ('ゲーム','原神','ナヒーダ',array['Nahida']::text[],8),
  ('ゲーム','崩壊:スターレイル','開拓者',array['Trailblazer']::text[],1),
  ('ゲーム','崩壊:スターレイル','三月なのか',array['March 7th']::text[],2),
  ('ゲーム','崩壊:スターレイル','丹恒',array['Dan Heng']::text[],3),
  ('ゲーム','崩壊:スターレイル','カフカ',array['Kafka']::text[],4),
  ('ゲーム','崩壊:スターレイル','刃',array['Blade']::text[],5),
  ('ゲーム','ゼンレスゾーンゼロ','アンビー',array['Anby']::text[],1),
  ('ゲーム','ゼンレスゾーンゼロ','ニコ',array['Nicole']::text[],2),
  ('ゲーム','ゼンレスゾーンゼロ','ビリー',array['Billy']::text[],3),
  ('ゲーム','ゼンレスゾーンゼロ','エレン',array['Ellen']::text[],4),
  ('ゲーム','Fate/Grand Order','マシュ・キリエライト',array['Mash Kyrielight']::text[],1),
  ('ゲーム','Fate/Grand Order','アルトリア・ペンドラゴン',array['Artoria Pendragon']::text[],2),
  ('ゲーム','Fate/Grand Order','ギルガメッシュ',array['Gilgamesh']::text[],3),
  ('ゲーム','Fate/Grand Order','ジャンヌ・ダルク',array['Jeanne d''Arc']::text[],4),
  ('ゲーム','アークナイツ','アーミヤ',array['Amiya']::text[],1),
  ('ゲーム','アークナイツ','チェン',array['Ch''en']::text[],2),
  ('ゲーム','アークナイツ','シルバーアッシュ',array['SilverAsh']::text[],3),
  ('ゲーム','ウマ娘 プリティーダービー','スペシャルウィーク',array['Special Week']::text[],1),
  ('ゲーム','ウマ娘 プリティーダービー','サイレンススズカ',array['Silence Suzuka']::text[],2),
  ('ゲーム','ウマ娘 プリティーダービー','トウカイテイオー',array['Tokai Teio']::text[],3),
  ('ゲーム','ウマ娘 プリティーダービー','オグリキャップ',array['Oguri Cap']::text[],4),
  -- キャラクターIP characters
  ('キャラクターIP','サンリオキャラクターズ','ハローキティ',array['HELLO KITTY']::text[],1),
  ('キャラクターIP','サンリオキャラクターズ','マイメロディ',array['MY MELODY']::text[],2),
  ('キャラクターIP','サンリオキャラクターズ','シナモロール',array['CINNAMOROLL']::text[],3),
  ('キャラクターIP','サンリオキャラクターズ','クロミ',array['KUROMI']::text[],4),
  ('キャラクターIP','サンリオキャラクターズ','ポムポムプリン',array['POMPOMPURIN']::text[],5),
  ('キャラクターIP','サンリオキャラクターズ','ポチャッコ',array['POCHACCO']::text[],6),
  ('キャラクターIP','サンリオキャラクターズ','ハンギョドン',array['HANGYODON']::text[],7),
  ('キャラクターIP','サンリオキャラクターズ','タキシードサム',array['TUXEDOSAM']::text[],8),
  ('キャラクターIP','ちいかわ','ちいかわ',array[]::text[],1),
  ('キャラクターIP','ちいかわ','ハチワレ',array[]::text[],2),
  ('キャラクターIP','ちいかわ','うさぎ',array[]::text[],3),
  ('キャラクターIP','ちいかわ','モモンガ',array[]::text[],4),
  ('キャラクターIP','ちいかわ','くりまんじゅう',array[]::text[],5),
  ('キャラクターIP','ちいかわ','ラッコ',array[]::text[],6),
  ('キャラクターIP','すみっコぐらし','しろくま',array[]::text[],1),
  ('キャラクターIP','すみっコぐらし','ぺんぎん？',array[]::text[],2),
  ('キャラクターIP','すみっコぐらし','とんかつ',array[]::text[],3),
  ('キャラクターIP','すみっコぐらし','ねこ',array[]::text[],4),
  ('キャラクターIP','すみっコぐらし','とかげ',array[]::text[],5),
  ('キャラクターIP','すみっコぐらし','えびふらいのしっぽ',array[]::text[],6),
  ('キャラクターIP','リラックマ','リラックマ',array[]::text[],1),
  ('キャラクターIP','リラックマ','コリラックマ',array[]::text[],2),
  ('キャラクターIP','リラックマ','キイロイトリ',array[]::text[],3),
  ('キャラクターIP','リラックマ','チャイロイコグマ',array[]::text[],4),
  ('キャラクターIP','ポケットモンスター','ピカチュウ',array['Pikachu']::text[],1),
  ('キャラクターIP','ポケットモンスター','イーブイ',array['Eevee']::text[],2),
  ('キャラクターIP','ポケットモンスター','リザードン',array['Charizard']::text[],3),
  ('キャラクターIP','ポケットモンスター','ゲンガー',array['Gengar']::text[],4),
  ('キャラクターIP','ポケットモンスター','カビゴン',array['Snorlax']::text[],5),
  ('キャラクターIP','ポケットモンスター','ポッチャマ',array['Piplup']::text[],6),
  ('キャラクターIP','星のカービィ','カービィ',array['Kirby']::text[],1),
  ('キャラクターIP','星のカービィ','ワドルディ',array['Waddle Dee']::text[],2),
  ('キャラクターIP','星のカービィ','メタナイト',array['Meta Knight']::text[],3),
  ('キャラクターIP','星のカービィ','デデデ大王',array['King Dedede']::text[],4),
  ('キャラクターIP','ディズニー ミッキー&フレンズ','ミッキーマウス',array['Mickey Mouse']::text[],1),
  ('キャラクターIP','ディズニー ミッキー&フレンズ','ミニーマウス',array['Minnie Mouse']::text[],2),
  ('キャラクターIP','ディズニー ミッキー&フレンズ','ドナルドダック',array['Donald Duck']::text[],3),
  ('キャラクターIP','ディズニー ミッキー&フレンズ','デイジーダック',array['Daisy Duck']::text[],4),
  ('キャラクターIP','ディズニー ミッキー&フレンズ','グーフィー',array['Goofy']::text[],5),
  ('キャラクターIP','ディズニー ミッキー&フレンズ','プルート',array['Pluto']::text[],6),
  ('キャラクターIP','PEANUTS','スヌーピー',array['Snoopy']::text[],1),
  ('キャラクターIP','PEANUTS','チャーリー・ブラウン',array['Charlie Brown']::text[],2),
  ('キャラクターIP','PEANUTS','ウッドストック',array['Woodstock']::text[],3),
  -- VTuber・配信者 members
  ('VTuber・配信者','にじさんじ','月ノ美兎',array['Tsukino Mito']::text[],1),
  ('VTuber・配信者','にじさんじ','樋口楓',array['Higuchi Kaede']::text[],2),
  ('VTuber・配信者','にじさんじ','剣持刀也',array['Kenmochi Toya']::text[],3),
  ('VTuber・配信者','にじさんじ','葛葉',array['Kuzuha']::text[],4),
  ('VTuber・配信者','にじさんじ','叶',array['Kanae']::text[],5),
  ('VTuber・配信者','にじさんじ','壱百満天原サロメ',array['Hyakumantenbara Salome']::text[],6),
  ('VTuber・配信者','にじさんじ','不破湊',array['Fuwa Minato']::text[],7),
  ('VTuber・配信者','hololive','ときのそら',array['Tokino Sora']::text[],1),
  ('VTuber・配信者','hololive','さくらみこ',array['Sakura Miko']::text[],2),
  ('VTuber・配信者','hololive','星街すいせい',array['Hoshimachi Suisei']::text[],3),
  ('VTuber・配信者','hololive','白上フブキ',array['Shirakami Fubuki']::text[],4),
  ('VTuber・配信者','hololive','兎田ぺこら',array['Usada Pekora']::text[],5),
  ('VTuber・配信者','hololive','宝鐘マリン',array['Houshou Marine']::text[],6),
  ('VTuber・配信者','hololive','常闇トワ',array['Tokoyami Towa']::text[],7),
  ('VTuber・配信者','ぶいすぽっ！','花芽すみれ',array['Kaga Sumire']::text[],1),
  ('VTuber・配信者','ぶいすぽっ！','一ノ瀬うるは',array['Ichinose Uruha']::text[],2),
  ('VTuber・配信者','ぶいすぽっ！','胡桃のあ',array['Kurumi Noah']::text[],3),
  ('VTuber・配信者','ぶいすぽっ！','橘ひなの',array['Tachibana Hinano']::text[],4),
  ('VTuber・配信者','ぶいすぽっ！','八雲べに',array['Yakumo Beni']::text[],5),
  ('VTuber・配信者','Neo-Porte','渋谷ハル',array['Shibuya HAL']::text[],1),
  ('VTuber・配信者','Neo-Porte','緋月ゆい',array['Hizuki Yui']::text[],2),
  ('VTuber・配信者','Neo-Porte','水無瀬',array['Minase']::text[],3),
  ('VTuber・配信者','TOP4','キヨ',array['Kiyo']::text[],1),
  ('VTuber・配信者','TOP4','レトルト',array['Retort']::text[],2),
  ('VTuber・配信者','TOP4','牛沢',array['Ushizawa']::text[],3),
  ('VTuber・配信者','TOP4','ガッチマン',array['Gatchman']::text[],4),
  ('VTuber・配信者','東海オンエア','てつや',array[]::text[],1),
  ('VTuber・配信者','東海オンエア','しばゆー',array[]::text[],2),
  ('VTuber・配信者','東海オンエア','りょう',array[]::text[],3),
  ('VTuber・配信者','東海オンエア','としみつ',array[]::text[],4),
  ('VTuber・配信者','東海オンエア','ゆめまる',array[]::text[],5),
  ('VTuber・配信者','東海オンエア','虫眼鏡',array[]::text[],6),
  -- お笑い members
  ('お笑い','令和ロマン','髙比良くるま',array[]::text[],1),
  ('お笑い','令和ロマン','松井ケムリ',array[]::text[],2),
  ('お笑い','真空ジェシカ','ガク',array[]::text[],1),
  ('お笑い','真空ジェシカ','川北茂澄',array[]::text[],2),
  ('お笑い','マユリカ','阪本',array[]::text[],1),
  ('お笑い','マユリカ','中谷',array[]::text[],2),
  ('お笑い','ぱーてぃーちゃん','すがちゃん最高No.1',array[]::text[],1),
  ('お笑い','ぱーてぃーちゃん','信子',array[]::text[],2),
  ('お笑い','ぱーてぃーちゃん','金子きょんちぃ',array[]::text[],3),
  ('お笑い','バッテリィズ','エース',array[]::text[],1),
  ('お笑い','バッテリィズ','寺家',array[]::text[],2),
  ('お笑い','ヤーレンズ','楢原真樹',array[]::text[],1),
  ('お笑い','ヤーレンズ','出井隼之介',array[]::text[],2),
  ('お笑い','エバース','佐々木隆史',array[]::text[],1),
  ('お笑い','エバース','町田和樹',array[]::text[],2),
  ('お笑い','ママタルト','檜原洋平',array[]::text[],1),
  ('お笑い','ママタルト','大鶴肥満',array[]::text[],2),
  ('お笑い','トム・ブラウン','布川ひろき',array[]::text[],1),
  ('お笑い','トム・ブラウン','みちお',array[]::text[],2),
  ('お笑い','ハナコ','菊田竜大',array[]::text[],1),
  ('お笑い','ハナコ','秋山寛貴',array[]::text[],2),
  ('お笑い','ハナコ','岡部大',array[]::text[],3),
  ('お笑い','かまいたち','山内健司',array[]::text[],1),
  ('お笑い','かまいたち','濱家隆一',array[]::text[],2),
  ('お笑い','霜降り明星','せいや',array[]::text[],1),
  ('お笑い','霜降り明星','粗品',array[]::text[],2),
  -- スポーツ players
  ('スポーツ','野球日本代表 侍ジャパン','大谷翔平',array['Shohei Ohtani']::text[],1),
  ('スポーツ','野球日本代表 侍ジャパン','山本由伸',array['Yoshinobu Yamamoto']::text[],2),
  ('スポーツ','野球日本代表 侍ジャパン','佐々木朗希',array['Roki Sasaki']::text[],3),
  ('スポーツ','野球日本代表 侍ジャパン','村上宗隆',array['Munetaka Murakami']::text[],4),
  ('スポーツ','野球日本代表 侍ジャパン','ダルビッシュ有',array['Yu Darvish']::text[],5),
  ('スポーツ','サッカー日本代表 SAMURAI BLUE','三笘薫',array['Kaoru Mitoma']::text[],1),
  ('スポーツ','サッカー日本代表 SAMURAI BLUE','久保建英',array['Takefusa Kubo']::text[],2),
  ('スポーツ','サッカー日本代表 SAMURAI BLUE','遠藤航',array['Wataru Endo']::text[],3),
  ('スポーツ','サッカー日本代表 SAMURAI BLUE','堂安律',array['Ritsu Doan']::text[],4),
  ('スポーツ','サッカー日本代表 SAMURAI BLUE','南野拓実',array['Takumi Minamino']::text[],5),
  ('スポーツ','バスケットボール日本代表 AKATSUKI JAPAN','河村勇輝',array['Yuki Kawamura']::text[],1),
  ('スポーツ','バスケットボール日本代表 AKATSUKI JAPAN','富樫勇樹',array['Yuki Togashi']::text[],2),
  ('スポーツ','バスケットボール日本代表 AKATSUKI JAPAN','比江島慎',array['Makoto Hiejima']::text[],3),
  ('スポーツ','バスケットボール日本代表 AKATSUKI JAPAN','渡邊雄太',array['Yuta Watanabe']::text[],4),
  ('スポーツ','バスケットボール日本代表 AKATSUKI JAPAN','八村塁',array['Rui Hachimura']::text[],5);

insert into public.characters_master (group_id, genre_id, name, aliases, display_order)
select
  gm.id,
  ge.id,
  sc.name,
  sc.aliases,
  sc.display_order
from _megrum_seed_characters sc
join public.genres_master ge on ge.name = sc.genre_name
join public.groups_master gm on gm.genre_id = ge.id and gm.name = sc.group_name
where not exists (
  select 1
  from public.characters_master c
  where c.group_id = gm.id
    and c.name = sc.name
);
