-- =====================================================================
-- iter168.38: 対象L1マスタのL2所属補完バッチ1
-- =====================================================================
-- K-POP男性/女性、国内男性/女性、キャラクターIP、スポーツの既存L1について、
-- 所属メンバー・キャラクターをレビューし、不足していたL2を追加する。

create temporary table _ihub_seed_characters (
  genre_name text not null,
  group_name text not null,
  name text not null,
  aliases text[] not null default '{}',
  display_order integer not null
) on commit drop;

insert into _ihub_seed_characters (genre_name, group_name, name, aliases, display_order) values
  ('K-POP女性', 'tripleS', 'クァク・ヨンジ', array[]::text[], 1),
  ('K-POP女性', 'tripleS', 'ニエン', array[]::text[], 2),
  ('K-POP女性', 'tripleS', 'パク・ソヒョン', array[]::text[], 3),
  ('K-POP女性', 'tripleS', 'シンユー', array[]::text[], 4),
  ('K-POP女性', 'tripleS', 'リン', array[]::text[], 5),
  ('K-POP女性', 'tripleS', 'ジュビン', array[]::text[], 6),
  ('K-POP女性', 'tripleS', 'チョン・ハヨン', array[]::text[], 7),
  ('K-POP女性', 'tripleS', 'パク・シオン', array[]::text[], 8),
  ('K-POP女性', 'tripleS', 'キム・チェウォン', array[]::text[], 9),
  ('K-POP女性', 'tripleS', 'ソルリン', array[]::text[], 10),
  ('K-POP女性', 'tripleS', 'ソア', array[]::text[], 11),
  ('K-POP女性', 'tripleS', 'チ・ソヨン', array[]::text[], 12),
  ('K-POP女性', 'Dreamcatcher', 'ダミ', array[]::text[], 1),
  ('K-POP女性', 'Dreamcatcher', 'ガヒョン', array[]::text[], 2),
  ('K-POP女性', 'WJSN', 'ルダ', array[]::text[], 1),
  ('K-POP女性', 'WJSN', 'ダウォン', array[]::text[], 2),
  ('K-POP女性', 'WJSN', 'ウンソ', array[]::text[], 3),
  ('K-POP女性', 'WJSN', 'ダヨン', array[]::text[], 4),
  ('K-POP女性', 'WJSN', 'ヨンジョン', array[]::text[], 5),
  ('K-POP女性', 'EVERGLOW', 'イロン', array[]::text[], 1),
  ('K-POP女性', 'Weeekly', 'ジハン', array[]::text[], 1),
  ('K-POP女性', 'izna', 'チェ・ジョンウン', array[]::text[], 1),
  ('K-POP女性', 'izna', 'チョン・セビ', array[]::text[], 2),
  ('K-POP男性', 'CRAVITY', 'ウォンジン', array[]::text[], 1),
  ('K-POP男性', 'CRAVITY', 'ウビン', array[]::text[], 2),
  ('K-POP男性', 'CRAVITY', 'テヨン', array[]::text[], 3),
  ('K-POP男性', 'CRAVITY', 'ソンミン', array[]::text[], 4),
  ('K-POP男性', 'SUPER JUNIOR', 'リョウク', array[]::text[], 1),
  ('K-POP男性', 'SUPER JUNIOR', 'キュヒョン', array[]::text[], 2),
  ('K-POP男性', 'SF9', 'ジュホ', array[]::text[], 1),
  ('K-POP男性', 'SF9', 'ユテヤン', array[]::text[], 2),
  ('K-POP男性', 'SF9', 'フィヨン', array[]::text[], 3),
  ('K-POP男性', 'EVNNE', 'ムン・ジョンヒョン', array[]::text[], 1),
  ('K-POP男性', 'EVNNE', 'パク・ジフ', array[]::text[], 2),
  ('K-POP男性', 'TEMPEST', 'LEW', array[]::text[], 1),
  ('K-POP男性', 'TEMPEST', 'テレ', array[]::text[], 2),
  ('国内男性', 'MAZZEL', 'TAKUTO', array[]::text[], 1),
  ('国内男性', 'MAZZEL', 'HAYATO', array[]::text[], 2),
  ('国内男性', 'MAZZEL', 'EIKI', array[]::text[], 3),
  ('国内男性', 'WATWING', '古幡亮', array[]::text[], 1),
  ('国内男性', 'OCTPATH', '小堀柊', array[]::text[], 1),
  ('国内男性', 'OCTPATH', '西島蓮汰', array[]::text[], 2),
  ('国内男性', 'DXTEEN', '福田歩汰', array[]::text[], 1),
  ('国内男性', 'LIL LEAGUE', '難波碧空', array[]::text[], 1),
  ('国内男性', 'BALLISTIK BOYZ', '松井利樹', array[]::text[], 1),
  ('国内男性', 'BALLISTIK BOYZ', '砂田将宏', array[]::text[], 2),
  ('国内男性', 'PSYCHIC FEVER', '半田龍臣', array[]::text[], 1),
  ('国内男性', 'PSYCHIC FEVER', 'WEESA', array[]::text[], 2),
  ('国内男性', 'BUDDiiS', 'YUMA', array[]::text[], 1),
  ('国内男性', 'BUDDiiS', 'SHOW', array[]::text[], 2),
  ('国内男性', 'BUDDiiS', 'TAKUYA', array[]::text[], 3),
  ('国内男性', 'BUDDiiS', 'HARUKI', array[]::text[], 4),
  ('国内男性', 'BUDDiiS', 'FUMIYA', array[]::text[], 5),
  ('国内女性', '乃木坂46', '愛宕心響', array[]::text[], 1),
  ('国内女性', '乃木坂46', '五百城茉央', array[]::text[], 2),
  ('国内女性', '乃木坂46', '池田瑛紗', array[]::text[], 3),
  ('国内女性', '乃木坂46', '一ノ瀬美空', array[]::text[], 4),
  ('国内女性', '乃木坂46', '伊藤理々杏', array[]::text[], 5),
  ('国内女性', '乃木坂46', '岩本蓮加', array[]::text[], 7),
  ('国内女性', '乃木坂46', '大越ひなの', array[]::text[], 10),
  ('国内女性', '乃木坂46', '岡本姫奈', array[]::text[], 11),
  ('国内女性', '乃木坂46', '小川彩', array[]::text[], 12),
  ('国内女性', '乃木坂46', '奥田いろは', array[]::text[], 13),
  ('国内女性', '乃木坂46', '小津玲奈', array[]::text[], 14),
  ('国内女性', '乃木坂46', '海邉朱莉', array[]::text[], 15),
  ('国内女性', '乃木坂46', '金川紗耶', array[]::text[], 17),
  ('国内女性', '乃木坂46', '川﨑桜', array[]::text[], 18),
  ('国内女性', '乃木坂46', '川端晃菜', array[]::text[], 19),
  ('国内女性', '乃木坂46', '黒見明香', array[]::text[], 20),
  ('国内女性', '乃木坂46', '柴田柚菜', array[]::text[], 21),
  ('国内女性', '乃木坂46', '菅原咲月', array[]::text[], 22),
  ('国内女性', '乃木坂46', '鈴木佑捺', array[]::text[], 23),
  ('国内女性', '乃木坂46', '瀬戸口心月', array[]::text[], 24),
  ('国内女性', '乃木坂46', '田村真佑', array[]::text[], 25),
  ('国内女性', '乃木坂46', '筒井あやめ', array[]::text[], 26),
  ('国内女性', '乃木坂46', '冨里奈央', array[]::text[], 27),
  ('国内女性', '乃木坂46', '長嶋凛桜', array[]::text[], 28),
  ('国内女性', '乃木坂46', '中西アルノ', array[]::text[], 29),
  ('国内女性', '乃木坂46', '林瑠奈', array[]::text[], 30),
  ('国内女性', '乃木坂46', '増田三莉音', array[]::text[], 31),
  ('国内女性', '乃木坂46', '森平麗心', array[]::text[], 32),
  ('国内女性', '乃木坂46', '矢田萌華', array[]::text[], 33),
  ('国内女性', '乃木坂46', '弓木奈於', array[]::text[], 34),
  ('国内女性', '乃木坂46', '吉田綾乃クリスティー', array[]::text[], 35),
  ('国内女性', '櫻坂46', '石森璃花', array[]::text[], 1),
  ('国内女性', '櫻坂46', '遠藤光莉', array[]::text[], 2),
  ('国内女性', '櫻坂46', '遠藤理子', array[]::text[], 3),
  ('国内女性', '櫻坂46', '大園玲', array[]::text[], 4),
  ('国内女性', '櫻坂46', '大沼晶保', array[]::text[], 5),
  ('国内女性', '櫻坂46', '小田倉麗奈', array[]::text[], 6),
  ('国内女性', '櫻坂46', '小池美波', array[]::text[], 7),
  ('国内女性', '櫻坂46', '幸阪茉里乃', array[]::text[], 8),
  ('国内女性', '櫻坂46', '小島凪紗', array[]::text[], 9),
  ('国内女性', '櫻坂46', '武元唯衣', array[]::text[], 10),
  ('国内女性', '櫻坂46', '谷口愛季', array[]::text[], 11),
  ('国内女性', '櫻坂46', '中嶋優月', array[]::text[], 13),
  ('国内女性', '櫻坂46', '増本綺良', array[]::text[], 15),
  ('国内女性', '櫻坂46', '松田里奈', array[]::text[], 16),
  ('国内女性', '櫻坂46', '的野美青', array[]::text[], 17),
  ('国内女性', '櫻坂46', '向井純葉', array[]::text[], 18),
  ('国内女性', '櫻坂46', '村井優', array[]::text[], 19),
  ('国内女性', '櫻坂46', '村山美羽', array[]::text[], 20),
  ('国内女性', '櫻坂46', '山下瞳月', array[]::text[], 24),
  ('国内女性', '櫻坂46', '浅井恋乃未', array[]::text[], 25),
  ('国内女性', '櫻坂46', '稲熊ひな', array[]::text[], 26),
  ('国内女性', '櫻坂46', '勝又春', array[]::text[], 27),
  ('国内女性', '櫻坂46', '佐藤愛桜', array[]::text[], 28),
  ('国内女性', '櫻坂46', '中川智尋', array[]::text[], 29),
  ('国内女性', '櫻坂46', '松本和子', array[]::text[], 30),
  ('国内女性', '櫻坂46', '目黒陽色', array[]::text[], 31),
  ('国内女性', '櫻坂46', '山川宇衣', array[]::text[], 32),
  ('国内女性', '櫻坂46', '山田桃実', array[]::text[], 33),
  ('国内女性', '日向坂46', '石塚瑶季', array[]::text[], 1),
  ('国内女性', '日向坂46', '上村ひなの', array[]::text[], 3),
  ('国内女性', '日向坂46', '小西夏菜実', array[]::text[], 5),
  ('国内女性', '日向坂46', '清水理央', array[]::text[], 6),
  ('国内女性', '日向坂46', '髙橋未来虹', array[]::text[], 8),
  ('国内女性', '日向坂46', '竹内希来里', array[]::text[], 9),
  ('国内女性', '日向坂46', '平尾帆夏', array[]::text[], 10),
  ('国内女性', '日向坂46', '平岡海月', array[]::text[], 11),
  ('国内女性', '日向坂46', '宮地すみれ', array[]::text[], 13),
  ('国内女性', '日向坂46', '森本茉莉', array[]::text[], 14),
  ('国内女性', '日向坂46', '山口陽世', array[]::text[], 15),
  ('国内女性', '日向坂46', '山下葉留花', array[]::text[], 16),
  ('国内女性', '日向坂46', '渡辺莉奈', array[]::text[], 17),
  ('国内女性', '日向坂46', '大田美月', array[]::text[], 18),
  ('国内女性', '日向坂46', '大野愛実', array[]::text[], 19),
  ('国内女性', '日向坂46', '片山紗希', array[]::text[], 20),
  ('国内女性', '日向坂46', '蔵盛妃那乃', array[]::text[], 21),
  ('国内女性', '日向坂46', '坂井新奈', array[]::text[], 22),
  ('国内女性', '日向坂46', '佐藤優羽', array[]::text[], 23),
  ('国内女性', '日向坂46', '下田衣珠季', array[]::text[], 24),
  ('国内女性', '日向坂46', '高井俐香', array[]::text[], 25),
  ('国内女性', '日向坂46', '鶴崎仁香', array[]::text[], 26),
  ('国内女性', '日向坂46', '松尾桜', array[]::text[], 27),
  ('国内女性', 'AKB48', '秋山由奈', array[]::text[], 1),
  ('国内女性', 'AKB48', '新井彩永', array[]::text[], 2),
  ('国内女性', 'AKB48', '岩立沙穂', array[]::text[], 3),
  ('国内女性', 'AKB48', '太田有紀', array[]::text[], 4),
  ('国内女性', 'AKB48', '大盛真歩', array[]::text[], 5),
  ('国内女性', 'AKB48', '工藤華純', array[]::text[], 7),
  ('国内女性', 'AKB48', '久保姫菜乃', array[]::text[], 8),
  ('国内女性', 'AKB48', '坂川陽香', array[]::text[], 10),
  ('国内女性', 'AKB48', '迫由芽実', array[]::text[], 11),
  ('国内女性', 'AKB48', '佐藤綺星', array[]::text[], 12),
  ('国内女性', 'AKB48', '下尾みう', array[]::text[], 13),
  ('国内女性', 'AKB48', '鈴木くるみ', array[]::text[], 14),
  ('国内女性', 'AKB48', '髙橋彩音', array[]::text[], 15),
  ('国内女性', 'AKB48', '田口愛佳', array[]::text[], 16),
  ('国内女性', 'AKB48', '徳永羚海', array[]::text[], 18),
  ('国内女性', 'AKB48', '長友彩海', array[]::text[], 19),
  ('国内女性', 'AKB48', '永野芹佳', array[]::text[], 20),
  ('国内女性', 'AKB48', '成田香姫奈', array[]::text[], 21),
  ('国内女性', 'AKB48', '橋本恵理子', array[]::text[], 22),
  ('国内女性', 'AKB48', '橋本陽菜', array[]::text[], 23),
  ('国内女性', 'AKB48', '畠山希美', array[]::text[], 24),
  ('国内女性', 'AKB48', '平田侑希', array[]::text[], 25),
  ('国内女性', 'AKB48', '福岡聖菜', array[]::text[], 26),
  ('国内女性', 'AKB48', '布袋百椛', array[]::text[], 27),
  ('国内女性', 'AKB48', '正鋳真優', array[]::text[], 28),
  ('国内女性', 'AKB48', '水島美結', array[]::text[], 29),
  ('国内女性', 'AKB48', '武藤小麟', array[]::text[], 31),
  ('国内女性', 'AKB48', '八木愛月', array[]::text[], 32),
  ('国内女性', 'AKB48', '山内瑞葵', array[]::text[], 33),
  ('国内女性', 'AKB48', '山口結愛', array[]::text[], 34),
  ('国内女性', 'AKB48', '山﨑空', array[]::text[], 35),
  ('国内女性', 'AKB48', '伊藤百花', array[]::text[], 36),
  ('国内女性', 'AKB48', '奥本カイリ', array[]::text[], 37),
  ('国内女性', 'AKB48', '川村結衣', array[]::text[], 38),
  ('国内女性', 'AKB48', '白鳥沙怜', array[]::text[], 39),
  ('国内女性', 'AKB48', '花田藍衣', array[]::text[], 40),
  ('国内女性', 'AKB48', '大賀彩姫', array[]::text[], 41),
  ('国内女性', 'AKB48', '近藤沙樹', array[]::text[], 42),
  ('国内女性', 'AKB48', '丸山ひなた', array[]::text[], 43),
  ('国内女性', 'SKE48', '相川暖花', array[]::text[], 1),
  ('国内女性', 'SKE48', '石黒友月', array[]::text[], 2),
  ('国内女性', 'SKE48', '伊藤虹々美', array[]::text[], 3),
  ('国内女性', 'SKE48', '入内嶋涼', array[]::text[], 4),
  ('国内女性', 'SKE48', '倉島杏実', array[]::text[], 6),
  ('国内女性', 'SKE48', '桒原椿', array[]::text[], 7),
  ('国内女性', 'SKE48', '杉本りいな', array[]::text[], 8),
  ('国内女性', 'SKE48', '鈴木恋奈', array[]::text[], 9),
  ('国内女性', 'SKE48', '野村実代', array[]::text[], 10),
  ('国内女性', 'SKE48', '原優寧', array[]::text[], 11),
  ('国内女性', 'SKE48', '松川みゆ', array[]::text[], 12),
  ('国内女性', 'SKE48', '南澤恋々', array[]::text[], 13),
  ('国内女性', 'SKE48', '山村さくら', array[]::text[], 14),
  ('国内女性', 'SKE48', '荒野姫楓', array[]::text[], 15),
  ('国内女性', 'SKE48', '池田楓', array[]::text[], 16),
  ('国内女性', 'SKE48', '伊藤実希', array[]::text[], 17),
  ('国内女性', 'SKE48', '井上瑠夏', array[]::text[], 18),
  ('国内女性', 'SKE48', '奥野心羽', array[]::text[], 19),
  ('国内女性', 'SKE48', '鎌田菜月', array[]::text[], 20),
  ('国内女性', 'SKE48', '北川愛乃', array[]::text[], 21),
  ('国内女性', 'SKE48', '雲井紗菜', array[]::text[], 22),
  ('国内女性', 'SKE48', '倉本羽菜', array[]::text[], 23),
  ('国内女性', 'SKE48', '近藤海琴', array[]::text[], 24),
  ('国内女性', 'SKE48', '佐藤佳穂', array[]::text[], 25),
  ('国内女性', 'SKE48', '篠原京香', array[]::text[], 26),
  ('国内女性', 'SKE48', '松本慈子', array[]::text[], 27),
  ('国内女性', 'SKE48', '青木莉樺', array[]::text[], 28),
  ('国内女性', 'SKE48', '赤堀君江', array[]::text[], 29),
  ('国内女性', 'SKE48', '浅井裕華', array[]::text[], 30),
  ('国内女性', 'SKE48', '井田玲音名', array[]::text[], 31),
  ('国内女性', 'SKE48', '太田彩夏', array[]::text[], 32),
  ('国内女性', 'SKE48', '太田愛恵', array[]::text[], 33),
  ('国内女性', 'SKE48', '大村杏', array[]::text[], 34),
  ('国内女性', 'SKE48', '河村優愛', array[]::text[], 35),
  ('国内女性', 'SKE48', '鈴木愛菜', array[]::text[], 36),
  ('国内女性', 'SKE48', '中坂美祐', array[]::text[], 37),
  ('国内女性', 'SKE48', '西井美桜', array[]::text[], 38),
  ('国内女性', 'SKE48', '長谷川雅', array[]::text[], 39),
  ('国内女性', 'SKE48', '森本くるみ', array[]::text[], 40),
  ('国内女性', 'SKE48', '川村昇子', array[]::text[], 41),
  ('国内女性', 'SKE48', '久保田怜', array[]::text[], 42),
  ('国内女性', 'SKE48', '桜井愛莉咲', array[]::text[], 43),
  ('国内女性', 'SKE48', '佐々木希美', array[]::text[], 44),
  ('国内女性', 'SKE48', '高村紗弥', array[]::text[], 45),
  ('国内女性', 'SKE48', '立花菖', array[]::text[], 46),
  ('国内女性', 'SKE48', '聖遥花', array[]::text[], 47),
  ('国内女性', 'SKE48', '福原心春', array[]::text[], 48),
  ('国内女性', 'SKE48', '宮本倫花', array[]::text[], 49),
  ('国内女性', 'SKE48', '横井志穂', array[]::text[], 50),
  ('国内女性', 'NMB48', '青原優花', array[]::text[], 1),
  ('国内女性', 'NMB48', '池帆乃香', array[]::text[], 3),
  ('国内女性', 'NMB48', '池田典愛', array[]::text[], 4),
  ('国内女性', 'NMB48', '石山千尋', array[]::text[], 5),
  ('国内女性', 'NMB48', '泉綾乃', array[]::text[], 6),
  ('国内女性', 'NMB48', '板垣心和', array[]::text[], 7),
  ('国内女性', 'NMB48', '内田愛彩', array[]::text[], 8),
  ('国内女性', 'NMB48', '岡腰星来', array[]::text[], 9),
  ('国内女性', 'NMB48', '衣笠彩実', array[]::text[], 10),
  ('国内女性', 'NMB48', '木根彩呂花', array[]::text[], 11),
  ('国内女性', 'NMB48', '黒島咲花', array[]::text[], 12),
  ('国内女性', 'NMB48', '坂下真心', array[]::text[], 13),
  ('国内女性', 'NMB48', '坂田心咲', array[]::text[], 14),
  ('国内女性', 'NMB48', '坂本理紗', array[]::text[], 15),
  ('国内女性', 'NMB48', '桜田彩叶', array[]::text[], 16),
  ('国内女性', 'NMB48', '新澤菜央', array[]::text[], 18),
  ('国内女性', 'NMB48', '高橋ことね', array[]::text[], 19),
  ('国内女性', 'NMB48', '竹田京加', array[]::text[], 20),
  ('国内女性', 'NMB48', '龍本弥生', array[]::text[], 21),
  ('国内女性', 'NMB48', '田中美空', array[]::text[], 22),
  ('国内女性', 'NMB48', '中川朋香', array[]::text[], 23),
  ('国内女性', 'NMB48', '西由真', array[]::text[], 24),
  ('国内女性', 'NMB48', '西島梨央', array[]::text[], 25),
  ('国内女性', 'NMB48', '西田帆花', array[]::text[], 26),
  ('国内女性', 'NMB48', '芳賀礼', array[]::text[], 27),
  ('国内女性', 'NMB48', '平山真衣', array[]::text[], 28),
  ('国内女性', 'NMB48', '福野杏実', array[]::text[], 29),
  ('国内女性', 'NMB48', '松岡さくら', array[]::text[], 30),
  ('国内女性', 'NMB48', '松本海日菜', array[]::text[], 31),
  ('国内女性', 'NMB48', '三鴨くるみ', array[]::text[], 32),
  ('国内女性', 'NMB48', '宮原心音', array[]::text[], 33),
  ('国内女性', 'NMB48', '宮本杏海', array[]::text[], 34),
  ('国内女性', 'NMB48', '村井悠莉', array[]::text[], 35),
  ('国内女性', 'NMB48', '吉見純音', array[]::text[], 36),
  ('国内女性', 'NMB48', '澁谷愛紗南', array[]::text[], 37),
  ('国内女性', 'NMB48', '田中ミリア', array[]::text[], 38),
  ('国内女性', 'NMB48', '宮崎紗衣', array[]::text[], 39),
  ('国内女性', 'NMB48', '山口美桜', array[]::text[], 40),
  ('国内女性', 'NMB48', '赤松昊', array[]::text[], 41),
  ('国内女性', 'NMB48', '桜井ひまり', array[]::text[], 42),
  ('国内女性', 'NMB48', '善家侑莉花', array[]::text[], 43),
  ('国内女性', 'NMB48', '高橋樹奈', array[]::text[], 44),
  ('国内女性', 'NMB48', '田中れい', array[]::text[], 45),
  ('国内女性', 'NMB48', '谷口詩乃', array[]::text[], 46),
  ('国内女性', 'NMB48', '西住美咲妃', array[]::text[], 47),
  ('国内女性', 'NMB48', '福原琴美', array[]::text[], 48),
  ('国内女性', 'NMB48', '藪内陽花', array[]::text[], 49),
  ('国内女性', 'NMB48', '和田承子', array[]::text[], 50),
  ('国内女性', 'HKT48', '生野莉奈', array[]::text[], 1),
  ('国内女性', 'HKT48', '石松結菜', array[]::text[], 3),
  ('国内女性', 'HKT48', '市村愛里', array[]::text[], 4),
  ('国内女性', 'HKT48', '北川陽彩', array[]::text[], 5),
  ('国内女性', 'HKT48', '栗原紗英', array[]::text[], 6),
  ('国内女性', 'HKT48', '渋井美奈', array[]::text[], 7),
  ('国内女性', 'HKT48', '中野南実', array[]::text[], 9),
  ('国内女性', 'HKT48', '藤野心葉', array[]::text[], 10),
  ('国内女性', 'HKT48', '渕上舞', array[]::text[], 11),
  ('国内女性', 'HKT48', '松永悠良', array[]::text[], 12),
  ('国内女性', 'HKT48', '梁瀬鈴雅', array[]::text[], 13),
  ('国内女性', 'HKT48', '山内祐奈', array[]::text[], 14),
  ('国内女性', 'HKT48', '龍頭綺音', array[]::text[], 15),
  ('国内女性', 'HKT48', '秋吉優花', array[]::text[], 16),
  ('国内女性', 'HKT48', '井澤美優', array[]::text[], 17),
  ('国内女性', 'HKT48', '石井彩音', array[]::text[], 18),
  ('国内女性', 'HKT48', '猪原絆愛', array[]::text[], 19),
  ('国内女性', 'HKT48', '今村麻莉愛', array[]::text[], 20),
  ('国内女性', 'HKT48', '江浦優香', array[]::text[], 21),
  ('国内女性', 'HKT48', '江口心々華', array[]::text[], 22),
  ('国内女性', 'HKT48', '大内梨果', array[]::text[], 23),
  ('国内女性', 'HKT48', '大庭凜咲', array[]::text[], 24),
  ('国内女性', 'HKT48', '栗山梨奈', array[]::text[], 25),
  ('国内女性', 'HKT48', '竹本くるみ', array[]::text[], 26),
  ('国内女性', 'HKT48', '立花心良', array[]::text[], 27),
  ('国内女性', 'HKT48', '田中伊桜莉', array[]::text[], 28),
  ('国内女性', 'HKT48', '福井可憐', array[]::text[], 29),
  ('国内女性', 'HKT48', '森﨑冴彩', array[]::text[], 30),
  ('国内女性', 'HKT48', '安井妃奈', array[]::text[], 31),
  ('国内女性', 'HKT48', '青木日菜子', array[]::text[], 32),
  ('国内女性', 'HKT48', '石川歩実優', array[]::text[], 33),
  ('国内女性', 'HKT48', '猪島莉玲亜', array[]::text[], 34),
  ('国内女性', 'HKT48', '呉優菜', array[]::text[], 35),
  ('国内女性', 'HKT48', '靏川那智', array[]::text[], 36),
  ('国内女性', 'HKT48', '長野らら', array[]::text[], 37),
  ('国内女性', 'HKT48', '松本苺花', array[]::text[], 38),
  ('国内女性', 'HKT48', '山川万里愛', array[]::text[], 39),
  ('国内女性', 'HKT48', '吉田めい', array[]::text[], 40),
  ('国内女性', 'STU48', '谷口茉妃菜', array[]::text[], 3),
  ('国内女性', 'STU48', '兵頭葵', array[]::text[], 4),
  ('国内女性', 'STU48', '福田朱里', array[]::text[], 5),
  ('国内女性', 'STU48', '池田裕楽', array[]::text[], 7),
  ('国内女性', 'STU48', '内海里音', array[]::text[], 8),
  ('国内女性', 'STU48', '尾崎世里花', array[]::text[], 9),
  ('国内女性', 'STU48', '川又優菜', array[]::text[], 10),
  ('国内女性', 'STU48', '工藤理子', array[]::text[], 11),
  ('国内女性', 'STU48', '迫姫華', array[]::text[], 12),
  ('国内女性', 'STU48', '清水紗良', array[]::text[], 13),
  ('国内女性', 'STU48', '高雄さやか', array[]::text[], 14),
  ('国内女性', 'STU48', '原田清花', array[]::text[], 15),
  ('国内女性', 'STU48', '宗雪里香', array[]::text[], 16),
  ('国内女性', 'STU48', '吉田彩良', array[]::text[], 17),
  ('国内女性', 'STU48', '渡辺菜月', array[]::text[], 18),
  ('国内女性', 'STU48', '岡田あずみ', array[]::text[], 19),
  ('国内女性', 'STU48', '岡村梨央', array[]::text[], 20),
  ('国内女性', 'STU48', '久留島優果', array[]::text[], 21),
  ('国内女性', 'STU48', '諸葛望愛', array[]::text[], 22),
  ('国内女性', 'STU48', '新井梨杏', array[]::text[], 23),
  ('国内女性', 'STU48', '石原侑奈', array[]::text[], 24),
  ('国内女性', 'STU48', '奥田唯菜', array[]::text[], 25),
  ('国内女性', 'STU48', '北澤苺', array[]::text[], 26),
  ('国内女性', 'STU48', '濵田響', array[]::text[], 27),
  ('国内女性', 'STU48', '森末妃奈', array[]::text[], 28),
  ('国内女性', 'STU48', '石松陽菜', array[]::text[], 29),
  ('国内女性', 'STU48', '井上久伶杏', array[]::text[], 30),
  ('国内女性', 'STU48', '木原姫花世', array[]::text[], 31),
  ('国内女性', 'STU48', '小松奈侑', array[]::text[], 32),
  ('国内女性', 'STU48', '坂木叶愛', array[]::text[], 33),
  ('国内女性', 'STU48', '坂崎愛', array[]::text[], 34),
  ('国内女性', 'STU48', '島田紗香', array[]::text[], 35),
  ('国内女性', 'STU48', '曽我部あこ', array[]::text[], 36),
  ('国内女性', 'STU48', '髙村栞里', array[]::text[], 37),
  ('国内女性', 'STU48', '田中奈菜子', array[]::text[], 38),
  ('国内女性', 'STU48', '道保琉南', array[]::text[], 39),
  ('国内女性', 'STU48', '野中莉央', array[]::text[], 40),
  ('国内女性', 'STU48', '濵田美惟', array[]::text[], 41),
  ('国内女性', 'STU48', '藤田愛結', array[]::text[], 42),
  ('国内女性', 'STU48', '屋木優菜', array[]::text[], 43),
  ('国内女性', 'STU48', '横井結菜', array[]::text[], 44),
  ('国内女性', '私立恵比寿中学', '小久保柚乃', array[]::text[], 1),
  ('国内女性', '私立恵比寿中学', '風見和香', array[]::text[], 2),
  ('国内女性', '私立恵比寿中学', '桜井えま', array[]::text[], 3),
  ('国内女性', '私立恵比寿中学', '仲村悠菜', array[]::text[], 4),
  ('国内女性', 'CUTIE STREET', '板倉可奈', array[]::text[], 1),
  ('国内女性', 'CUTIE STREET', '増田彩乃', array[]::text[], 2),
  ('国内女性', 'CUTIE STREET', '真鍋凪咲', array[]::text[], 3),
  ('国内女性', '高嶺のなでしこ', '東山恵里沙', array[]::text[], 1),
  ('国内女性', '高嶺のなでしこ', '日向端ひな', array[]::text[], 2),
  ('国内女性', '高嶺のなでしこ', '星谷美来', array[]::text[], 3),
  ('国内女性', '高嶺のなでしこ', '籾山ひめり', array[]::text[], 4),
  ('国内女性', 'iLiFE!', '空詩かれん', array[]::text[], 1),
  ('国内女性', 'iLiFE!', '恋星はるか', array[]::text[], 2),
  ('国内女性', 'iLiFE!', '純嶺みき', array[]::text[], 3),
  ('国内女性', 'iLiFE!', '福丸うさ', array[]::text[], 4),
  ('国内女性', 'iLiFE!', '小こ熊ぐままむ', array[]::text[], 5),
  ('国内女性', 'iLiFE!', '小羽みに', array[]::text[], 6),
  ('国内女性', 'モーニング娘。', '岡村ほまれ', array[]::text[], 4),
  ('国内女性', 'モーニング娘。', '山﨑愛生', array[]::text[], 5),
  ('国内女性', 'モーニング娘。', '櫻井梨央', array[]::text[], 6),
  ('国内女性', 'モーニング娘。', '井上春華', array[]::text[], 7),
  ('国内女性', 'モーニング娘。', '弓桁朱琴', array[]::text[], 8),
  ('国内女性', 'モーニング娘。', '杉原明紗', array[]::text[], 9),
  ('国内女性', 'アンジュルム', '為永幸音', array[]::text[], 2),
  ('国内女性', 'アンジュルム', '川名凜', array[]::text[], 4),
  ('国内女性', 'アンジュルム', '松本わかな', array[]::text[], 5),
  ('国内女性', 'アンジュルム', '平山遊季', array[]::text[], 6),
  ('国内女性', 'アンジュルム', '下井谷幸穂', array[]::text[], 7),
  ('国内女性', 'アンジュルム', '後藤花', array[]::text[], 8),
  ('国内女性', 'アンジュルム', '長野桃羽', array[]::text[], 9),
  ('国内女性', 'Juice=Juice', '入江里咲', array[]::text[], 6),
  ('国内女性', 'Juice=Juice', '江端妃咲', array[]::text[], 7),
  ('国内女性', 'Juice=Juice', '石山咲良', array[]::text[], 8),
  ('国内女性', 'Juice=Juice', '遠藤彩加里', array[]::text[], 9),
  ('国内女性', 'Juice=Juice', '川嶋美楓', array[]::text[], 10),
  ('国内女性', 'Juice=Juice', '林仁愛', array[]::text[], 11),
  ('国内女性', '超ときめき♡宣伝部', '吉川ひより', array[]::text[], 1),
  ('国内女性', 'Appare!', '永堀ゆめ', array[]::text[], 1),
  ('国内女性', 'Appare!', '藤宮めい', array[]::text[], 2),
  ('国内女性', 'Appare!', '工藤のか', array[]::text[], 3),
  ('国内女性', 'BEYOOOOONDS', '前田こころ', array[]::text[], 4),
  ('国内女性', 'BEYOOOOONDS', '岡村美波', array[]::text[], 5),
  ('国内女性', 'BEYOOOOONDS', '清野桃々姫', array[]::text[], 6),
  ('国内女性', 'BEYOOOOONDS', '平井美葉', array[]::text[], 7),
  ('国内女性', 'BEYOOOOONDS', '小林萌花', array[]::text[], 8),
  ('国内女性', 'BEYOOOOONDS', '里吉うたの', array[]::text[], 9),
  ('国内女性', 'つばきファクトリー', '福田真琳', array[]::text[], 6),
  ('国内女性', 'つばきファクトリー', '豫風瑠乃', array[]::text[], 7),
  ('国内女性', 'つばきファクトリー', '石井泉羽', array[]::text[], 8),
  ('国内女性', 'つばきファクトリー', '村田結生', array[]::text[], 9),
  ('国内女性', 'つばきファクトリー', '土居楓奏', array[]::text[], 10),
  ('国内女性', 'つばきファクトリー', '西村乙輝', array[]::text[], 11),
  ('国内女性', 'OCHA NORMA', '中山夏月姫', array[]::text[], 5),
  ('国内女性', 'OCHA NORMA', '西﨑美空', array[]::text[], 6),
  ('国内女性', 'OCHA NORMA', '北原もも', array[]::text[], 7),
  ('国内女性', 'OCHA NORMA', '筒井澪心', array[]::text[], 8),
  ('キャラクターIP', 'サンリオキャラクターズ', 'ぐでたま', array[]::text[], 1),
  ('キャラクターIP', 'サンリオキャラクターズ', 'まるもふびより', array[]::text[], 2),
  ('キャラクターIP', 'サンリオキャラクターズ', 'ぼんぼんりぼん', array[]::text[], 3),
  ('キャラクターIP', 'サンリオキャラクターズ', 'マロンクリーム', array[]::text[], 4),
  ('キャラクターIP', 'サンリオキャラクターズ', 'みんなのたあ坊', array[]::text[], 5),
  ('キャラクターIP', 'サンリオキャラクターズ', 'ぽこぽん日記', array[]::text[], 6),
  ('キャラクターIP', 'サンリオキャラクターズ', 'チアリーチャム', array[]::text[], 7),
  ('キャラクターIP', 'サンリオキャラクターズ', 'ウサハナ', array[]::text[], 8),
  ('キャラクターIP', 'サンリオキャラクターズ', 'シュガーバニーズ', array[]::text[], 9),
  ('キャラクターIP', 'サンリオキャラクターズ', 'パティ&ジミー', array[]::text[], 10),
  ('キャラクターIP', 'サンリオキャラクターズ', 'マイスウィートピアノ', array[]::text[], 11),
  ('キャラクターIP', 'ポケットモンスター', 'ゼニガメ', array[]::text[], 1),
  ('キャラクターIP', 'ポケットモンスター', 'フシギダネ', array[]::text[], 2),
  ('キャラクターIP', 'ポケットモンスター', 'カイリュー', array[]::text[], 3),
  ('キャラクターIP', 'ポケットモンスター', 'デデンネ', array[]::text[], 4),
  ('キャラクターIP', 'ポケットモンスター', 'ヤドン', array[]::text[], 5),
  ('キャラクターIP', 'ポケットモンスター', 'ラプラス', array[]::text[], 6),
  ('キャラクターIP', 'ポケットモンスター', 'メタモン', array[]::text[], 7),
  ('キャラクターIP', 'ポケットモンスター', 'コダック', array[]::text[], 8),
  ('キャラクターIP', 'ポケットモンスター', 'アローラロコン', array[]::text[], 9),
  ('キャラクターIP', 'ポケットモンスター', 'ニャオハ', array[]::text[], 10),
  ('キャラクターIP', 'ポケットモンスター', 'クワッス', array[]::text[], 11),
  ('キャラクターIP', 'ポケットモンスター', 'パモ', array[]::text[], 12),
  ('キャラクターIP', 'ポケットモンスター', 'エーフィ', array[]::text[], 13),
  ('キャラクターIP', 'ポケットモンスター', 'ブラッキー', array[]::text[], 14),
  ('キャラクターIP', '星のカービィ', 'リック', array[]::text[], 1),
  ('キャラクターIP', '星のカービィ', 'カイン', array[]::text[], 2),
  ('キャラクターIP', '星のカービィ', 'クー', array[]::text[], 3),
  ('キャラクターIP', '星のカービィ', 'アドレーヌ', array[]::text[], 4),
  ('キャラクターIP', '星のカービィ', 'ワドルドゥ', array[]::text[], 5),
  ('キャラクターIP', 'ディズニー ミッキー&フレンズ', 'チップ', array[]::text[], 1),
  ('キャラクターIP', 'ディズニー ミッキー&フレンズ', 'デール', array[]::text[], 2),
  ('キャラクターIP', 'ディズニー ミッキー&フレンズ', 'クラリス', array[]::text[], 3),
  ('キャラクターIP', 'ディズニー ミッキー&フレンズ', 'マックス', array[]::text[], 4),
  ('キャラクターIP', 'ディズニー ミッキー&フレンズ', 'ヒューイ', array[]::text[], 5),
  ('キャラクターIP', 'ディズニー ミッキー&フレンズ', 'デューイ', array[]::text[], 6),
  ('キャラクターIP', 'ディズニー ミッキー&フレンズ', 'ルーイ', array[]::text[], 7),
  ('キャラクターIP', 'ミッフィー', 'ダーン', array[]::text[], 1),
  ('キャラクターIP', 'ミッフィー', 'グランティ', array[]::text[], 2),
  ('キャラクターIP', 'ミッフィー', 'ポピー', array[]::text[], 3),
  ('キャラクターIP', 'ミッフィー', 'アリスおばさん', array[]::text[], 4),
  ('キャラクターIP', 'PEANUTS', 'シュローダー', array[]::text[], 1),
  ('キャラクターIP', 'PEANUTS', 'ペパーミントパティ', array[]::text[], 2),
  ('キャラクターIP', 'PEANUTS', 'マーシー', array[]::text[], 3),
  ('キャラクターIP', 'PEANUTS', 'フランクリン', array[]::text[], 4),
  ('キャラクターIP', 'mofusand', 'にゃんこ', array[]::text[], 1),
  ('キャラクターIP', 'mofusand', 'ひつじにゃん', array[]::text[], 2),
  ('キャラクターIP', 'mofusand', 'パンにゃん', array[]::text[], 3),
  ('キャラクターIP', 'mofusand', 'くまにゃん', array[]::text[], 4),
  ('キャラクターIP', 'たまごっち', 'みみっち', array[]::text[], 1),
  ('キャラクターIP', 'たまごっち', 'ござるっち', array[]::text[], 2),
  ('キャラクターIP', 'たまごっち', 'ふらわっち', array[]::text[], 3),
  ('キャラクターIP', 'たまごっち', 'ラブリっち', array[]::text[], 4),
  ('キャラクターIP', 'たまごっち', 'メロディっち', array[]::text[], 5),
  ('キャラクターIP', 'たまごっち', 'くろまめっち', array[]::text[], 6),
  ('キャラクターIP', 'たまごっち', 'まきこ', array[]::text[], 7),
  ('キャラクターIP', 'たまごっち', 'しまぐるっち', array[]::text[], 8),
  ('キャラクターIP', 'シルバニアファミリー', 'ショコラウサギの赤ちゃん', array[]::text[], 1),
  ('キャラクターIP', 'シルバニアファミリー', 'ペルシャネコの女の子', array[]::text[], 2),
  ('キャラクターIP', 'シルバニアファミリー', 'くるみリスの女の子', array[]::text[], 3),
  ('キャラクターIP', 'シルバニアファミリー', 'シカの赤ちゃん', array[]::text[], 4),
  ('キャラクターIP', 'シルバニアファミリー', 'ラブラドールの赤ちゃん', array[]::text[], 5),
  ('キャラクターIP', 'リカちゃん', 'いづみちゃん', array[]::text[], 1),
  ('キャラクターIP', 'リカちゃん', 'かけるくん', array[]::text[], 2),
  ('キャラクターIP', 'リカちゃん', 'みきちゃん', array[]::text[], 3),
  ('キャラクターIP', 'リカちゃん', 'まきちゃん', array[]::text[], 4),
  ('キャラクターIP', 'リカちゃん', 'リカちゃんパパ', array[]::text[], 5),
  ('キャラクターIP', 'リカちゃん', 'リカちゃんママ', array[]::text[], 6),
  ('キャラクターIP', 'PUI PUI モルカー', 'テディ', array[]::text[], 1),
  ('キャラクターIP', 'PUI PUI モルカー', 'チョコ', array[]::text[], 2),
  ('キャラクターIP', 'PUI PUI モルカー', '救急モルカー', array[]::text[], 3),
  ('キャラクターIP', 'PUI PUI モルカー', 'パトモルカー', array[]::text[], 4),
  ('キャラクターIP', 'ピングー', 'ロビ', array[]::text[], 1),
  ('キャラクターIP', 'ピングー', 'ピンギ', array[]::text[], 2),
  ('キャラクターIP', 'こぎみゅん', 'コギムーナ', array[]::text[], 1),
  ('キャラクターIP', 'こぎみゅん', 'チョココロネェ', array[]::text[], 2),
  ('キャラクターIP', 'こぎみゅん', 'ぎょうざくん', array[]::text[], 3),
  ('スポーツ', '野球日本代表 侍ジャパン', '牧秀悟', array[]::text[], 1),
  ('スポーツ', '野球日本代表 侍ジャパン', '岡本和真', array[]::text[], 2),
  ('スポーツ', '野球日本代表 侍ジャパン', '源田壮亮', array[]::text[], 3),
  ('スポーツ', '野球日本代表 侍ジャパン', '近藤健介', array[]::text[], 4),
  ('スポーツ', '野球日本代表 侍ジャパン', '今永昇太', array[]::text[], 5),
  ('スポーツ', '野球日本代表 侍ジャパン', '栗山英樹', array[]::text[], 6),
  ('スポーツ', '野球日本代表 侍ジャパン', '甲斐拓也', array[]::text[], 7),
  ('スポーツ', '野球日本代表 侍ジャパン', '吉田正尚', array[]::text[], 8),
  ('スポーツ', '野球日本代表 侍ジャパン', '戸郷翔征', array[]::text[], 9),
  ('スポーツ', '野球日本代表 侍ジャパン', '才木浩人', array[]::text[], 10),
  ('スポーツ', 'サッカー日本代表 SAMURAI BLUE', '伊東純也', array[]::text[], 1),
  ('スポーツ', 'サッカー日本代表 SAMURAI BLUE', '前田大然', array[]::text[], 2),
  ('スポーツ', 'サッカー日本代表 SAMURAI BLUE', '鎌田大地', array[]::text[], 3),
  ('スポーツ', 'サッカー日本代表 SAMURAI BLUE', '守田英正', array[]::text[], 4),
  ('スポーツ', 'サッカー日本代表 SAMURAI BLUE', '田中碧', array[]::text[], 5),
  ('スポーツ', 'サッカー日本代表 SAMURAI BLUE', '上田綺世', array[]::text[], 6),
  ('スポーツ', 'サッカー日本代表 SAMURAI BLUE', '冨安健洋', array[]::text[], 7),
  ('スポーツ', 'サッカー日本代表 SAMURAI BLUE', '板倉滉', array[]::text[], 8),
  ('スポーツ', 'サッカー日本代表 SAMURAI BLUE', '菅原由勢', array[]::text[], 9),
  ('スポーツ', 'サッカー日本代表 SAMURAI BLUE', '鈴木彩艶', array[]::text[], 10),
  ('スポーツ', 'バスケットボール日本代表 AKATSUKI JAPAN', '富永啓生', array[]::text[], 1),
  ('スポーツ', 'バスケットボール日本代表 AKATSUKI JAPAN', '馬場雄大', array[]::text[], 2),
  ('スポーツ', 'バスケットボール日本代表 AKATSUKI JAPAN', 'ジョシュ・ホーキンソン', array[]::text[], 3),
  ('スポーツ', 'バスケットボール日本代表 AKATSUKI JAPAN', 'ジェイコブス晶', array[]::text[], 4),
  ('スポーツ', 'バスケットボール日本代表 AKATSUKI JAPAN', '吉井裕鷹', array[]::text[], 5),
  ('スポーツ', 'バスケットボール日本代表 AKATSUKI JAPAN', '渡邉飛勇', array[]::text[], 6),
  ('スポーツ', '阪神タイガース', 'ラッキー', array[]::text[], 1),
  ('スポーツ', '阪神タイガース', 'キー太', array[]::text[], 2),
  ('スポーツ', '阪神タイガース', '近本光司', array[]::text[], 3),
  ('スポーツ', '阪神タイガース', '中野拓夢', array[]::text[], 4),
  ('スポーツ', '阪神タイガース', '佐藤輝明', array[]::text[], 5),
  ('スポーツ', '阪神タイガース', '大山悠輔', array[]::text[], 6),
  ('スポーツ', '阪神タイガース', '森下翔太', array[]::text[], 7),
  ('スポーツ', '阪神タイガース', '才木浩人', array[]::text[], 8),
  ('スポーツ', '阪神タイガース', '村上頌樹', array[]::text[], 9),
  ('スポーツ', '読売ジャイアンツ', 'シスタージャビット', array[]::text[], 1),
  ('スポーツ', '読売ジャイアンツ', '岡本和真', array[]::text[], 2),
  ('スポーツ', '読売ジャイアンツ', '坂本勇人', array[]::text[], 3),
  ('スポーツ', '読売ジャイアンツ', '丸佳浩', array[]::text[], 4),
  ('スポーツ', '読売ジャイアンツ', '戸郷翔征', array[]::text[], 5),
  ('スポーツ', '読売ジャイアンツ', '大勢', array[]::text[], 6),
  ('スポーツ', '読売ジャイアンツ', '吉川尚輝', array[]::text[], 7),
  ('スポーツ', '東京ヤクルトスワローズ', 'つばみ', array[]::text[], 1),
  ('スポーツ', '東京ヤクルトスワローズ', 'トルクーヤ', array[]::text[], 2),
  ('スポーツ', '東京ヤクルトスワローズ', '村上宗隆', array[]::text[], 3),
  ('スポーツ', '東京ヤクルトスワローズ', '山田哲人', array[]::text[], 4),
  ('スポーツ', '東京ヤクルトスワローズ', '長岡秀樹', array[]::text[], 5),
  ('スポーツ', '東京ヤクルトスワローズ', '塩見泰隆', array[]::text[], 6),
  ('スポーツ', '東京ヤクルトスワローズ', '小川泰弘', array[]::text[], 7),
  ('スポーツ', 'オリックス・バファローズ', 'バファローベル', array[]::text[], 1),
  ('スポーツ', 'オリックス・バファローズ', '宮城大弥', array[]::text[], 2),
  ('スポーツ', 'オリックス・バファローズ', '山岡泰輔', array[]::text[], 3),
  ('スポーツ', 'オリックス・バファローズ', '宗佑磨', array[]::text[], 4),
  ('スポーツ', 'オリックス・バファローズ', '紅林弘太郎', array[]::text[], 5),
  ('スポーツ', 'オリックス・バファローズ', '頓宮裕真', array[]::text[], 6),
  ('スポーツ', '北海道日本ハムファイターズ', 'ポリー', array[]::text[], 1),
  ('スポーツ', '北海道日本ハムファイターズ', 'カビー', array[]::text[], 2),
  ('スポーツ', '北海道日本ハムファイターズ', '伊藤大海', array[]::text[], 3),
  ('スポーツ', '北海道日本ハムファイターズ', '万波中正', array[]::text[], 4),
  ('スポーツ', '北海道日本ハムファイターズ', '清宮幸太郎', array[]::text[], 5),
  ('スポーツ', '北海道日本ハムファイターズ', '松本剛', array[]::text[], 6),
  ('スポーツ', '北海道日本ハムファイターズ', '水谷瞬', array[]::text[], 7),
  ('スポーツ', '福岡ソフトバンクホークス', 'ハニーホーク', array[]::text[], 1),
  ('スポーツ', '福岡ソフトバンクホークス', '柳田悠岐', array[]::text[], 2),
  ('スポーツ', '福岡ソフトバンクホークス', '栗原陵矢', array[]::text[], 3),
  ('スポーツ', '福岡ソフトバンクホークス', '周東佑京', array[]::text[], 4),
  ('スポーツ', '福岡ソフトバンクホークス', '近藤健介', array[]::text[], 5),
  ('スポーツ', '福岡ソフトバンクホークス', '今宮健太', array[]::text[], 6),
  ('スポーツ', '浦和レッズ', 'フレンディア', array[]::text[], 1),
  ('スポーツ', '浦和レッズ', '西川周作', array[]::text[], 2),
  ('スポーツ', '浦和レッズ', '酒井宏樹', array[]::text[], 3),
  ('スポーツ', '浦和レッズ', '関根貴大', array[]::text[], 4),
  ('スポーツ', '浦和レッズ', '渡邊凌磨', array[]::text[], 5),
  ('スポーツ', '鹿島アントラーズ', 'しかこ', array[]::text[], 1),
  ('スポーツ', '鹿島アントラーズ', 'アントン', array[]::text[], 2),
  ('スポーツ', '鹿島アントラーズ', '鈴木優磨', array[]::text[], 3),
  ('スポーツ', '鹿島アントラーズ', '知念慶', array[]::text[], 4),
  ('スポーツ', '鹿島アントラーズ', '早川友基', array[]::text[], 5),
  ('スポーツ', '横浜F・マリノス', 'マリノス君', array[]::text[], 1),
  ('スポーツ', '横浜F・マリノス', 'ワルノス', array[]::text[], 2),
  ('スポーツ', '横浜F・マリノス', '喜田拓也', array[]::text[], 3),
  ('スポーツ', '横浜F・マリノス', '天野純', array[]::text[], 4),
  ('スポーツ', '横浜F・マリノス', '植中朝日', array[]::text[], 5),
  ('スポーツ', '川崎フロンターレ', 'カブレラ', array[]::text[], 1),
  ('スポーツ', '川崎フロンターレ', 'ワルンタ', array[]::text[], 2),
  ('スポーツ', '川崎フロンターレ', '脇坂泰斗', array[]::text[], 3),
  ('スポーツ', '川崎フロンターレ', '家長昭博', array[]::text[], 4),
  ('スポーツ', '川崎フロンターレ', '山田新', array[]::text[], 5),
  ('スポーツ', 'ヴィッセル神戸', '武藤嘉紀', array[]::text[], 1),
  ('スポーツ', 'ヴィッセル神戸', '大迫勇也', array[]::text[], 2),
  ('スポーツ', 'ヴィッセル神戸', '山口蛍', array[]::text[], 3),
  ('スポーツ', 'ヴィッセル神戸', '酒井高徳', array[]::text[], 4),
  ('スポーツ', '千葉ジェッツ', '富樫勇樹', array[]::text[], 1),
  ('スポーツ', '千葉ジェッツ', '原修太', array[]::text[], 2),
  ('スポーツ', '千葉ジェッツ', '西村文男', array[]::text[], 3),
  ('スポーツ', '宇都宮ブレックス', 'ベリーちゃん', array[]::text[], 1),
  ('スポーツ', '宇都宮ブレックス', '比江島慎', array[]::text[], 2),
  ('スポーツ', '宇都宮ブレックス', '遠藤祐亮', array[]::text[], 3),
  ('スポーツ', '宇都宮ブレックス', '田臥勇太', array[]::text[], 4),
  ('スポーツ', 'アルバルク東京', 'テーブス海', array[]::text[], 1),
  ('スポーツ', 'アルバルク東京', 'ザック・バランスキー', array[]::text[], 2),
  ('スポーツ', 'アルバルク東京', '小酒部泰暉', array[]::text[], 3),
  ('スポーツ', '琉球ゴールデンキングス', '岸本隆一', array[]::text[], 1),
  ('スポーツ', '琉球ゴールデンキングス', '今村佳太', array[]::text[], 2),
  ('スポーツ', '琉球ゴールデンキングス', '小野寺祥太', array[]::text[], 3),
  ('スポーツ', '横浜ビー・コルセアーズ', '河村勇輝', array[]::text[], 1),
  ('スポーツ', '横浜ビー・コルセアーズ', '森井健太', array[]::text[], 2),
  ('スポーツ', '横浜ビー・コルセアーズ', '須藤昂矢', array[]::text[], 3);

insert into public.characters_master (group_id, genre_id, name, aliases, display_order)
select
  gm.id,
  ge.id,
  sc.name,
  sc.aliases,
  sc.display_order
from _ihub_seed_characters sc
join public.genres_master ge on ge.name = sc.genre_name
join public.groups_master gm on gm.genre_id = ge.id and gm.name = sc.group_name
where not exists (
  select 1
  from public.characters_master c
  where c.group_id = gm.id
    and c.name = sc.name
);

with selectable_members as (
  select
    case
      when gm.kind = 'work'
        or ge.name in ('アニメ・マンガ', 'ゲーム', 'キャラクターIP', '2.5次元・舞台')
        then 'character'
      else 'person'
    end as entity_type,
    case
      when gm.kind = 'work'
        or ge.name in ('アニメ・マンガ', 'ゲーム', 'キャラクターIP', '2.5次元・舞台')
        then 'character:' || ge.name || ':' || coalesce(gm.name, '_none') || ':' || cm.name
      else 'person:member:' || ge.name || ':' || coalesce(gm.name, '_none') || ':' || cm.name
    end as identity_key,
    cm.name as canonical_name,
    cm.aliases,
    cm.display_order
  from public.characters_master cm
  join public.groups_master gm on gm.id = cm.group_id
  join public.genres_master ge on ge.id = cm.genre_id
  where ge.name in ('K-POP男性','K-POP女性','国内男性','国内女性','キャラクターIP','スポーツ')
),
entity_seed as (
  select identity_key, canonical_name, entity_type, aliases, display_order
  from selectable_members
)
insert into public.oshi_entities_master (
  identity_key,
  canonical_name,
  entity_type,
  aliases,
  display_order
)
select
  identity_key,
  canonical_name,
  entity_type,
  array(
    select distinct alias
    from unnest(coalesce(aliases, '{}'::text[])) as a(alias)
    where btrim(alias) <> ''
    order by alias
  ) as aliases,
  min(display_order) as display_order
from entity_seed
where btrim(identity_key) <> ''
  and btrim(canonical_name) <> ''
group by identity_key, canonical_name, entity_type, aliases
on conflict (identity_key) do update
  set canonical_name = excluded.canonical_name,
      entity_type = excluded.entity_type,
      aliases = array(
        select distinct alias
        from unnest(
          coalesce(public.oshi_entities_master.aliases, '{}'::text[])
          || coalesce(excluded.aliases, '{}'::text[])
        ) as a(alias)
        where btrim(alias) <> ''
        order by alias
      );

with member_entities as (
  select
    cm.id as character_id,
    case
      when gm.kind = 'work'
        or ge.name in ('アニメ・マンガ', 'ゲーム', 'キャラクターIP', '2.5次元・舞台')
        then 'character:' || ge.name || ':' || coalesce(gm.name, '_none') || ':' || cm.name
      else 'person:member:' || ge.name || ':' || coalesce(gm.name, '_none') || ':' || cm.name
    end as identity_key
  from public.characters_master cm
  join public.groups_master gm on gm.id = cm.group_id
  join public.genres_master ge on ge.id = cm.genre_id
  where ge.name in ('K-POP男性','K-POP女性','国内男性','国内女性','キャラクターIP','スポーツ')
)
update public.characters_master cm
set entity_id = e.id
from member_entities me
join public.oshi_entities_master e on e.identity_key = me.identity_key
where cm.id = me.character_id
  and cm.entity_id is distinct from e.id;
